"""Per-company enrichment: 8-quarter financials, news signals, sources.

Hand-populated from the multi-agent research turns (June 2026) for the top
priority companies. Lower-priority companies remain at the base seed level
and will be filled by parallel agent fan-out in the next iteration.

Idempotent — re-running won't duplicate. To refresh: DELETE rows for that
company_id from target_quarterly / target_signals / target_sources and
re-run.
"""

ENRICHMENT = {

    # ─────────────────────────────────────────────────────────────────
    "omaxe": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹536 cr", "ebitda": "−₹146 cr", "ebitda_pct": "−27%",  "pat": "−₹144 cr"},
            {"label": "Q2 FY25", "revenue": "₹342 cr", "ebitda": "−₹151 cr", "ebitda_pct": "−44%",  "pat": "−₹147 cr"},
            {"label": "Q3 FY25", "revenue": "₹389 cr", "ebitda": "−₹224 cr", "ebitda_pct": "−58%",  "pat": "−₹239 cr",  "note": "Largest loss; possible impairment"},
            {"label": "Q4 FY25", "revenue": "₹289 cr", "ebitda": "−₹127 cr", "ebitda_pct": "−44%",  "pat": "−₹150 cr"},
            {"label": "Q1 FY26", "revenue": "₹541 cr", "ebitda": "−₹106 cr", "ebitda_pct": "−20%",  "pat": "−₹149 cr"},
            {"label": "Q2 FY26", "revenue": "₹282 cr", "ebitda": "−₹170 cr", "ebitda_pct": "−60%",  "pat": "−₹186 cr",  "note": "Worst OPM in series"},
            {"label": "Q3 FY26", "revenue": "₹354 cr", "ebitda": "−₹153 cr", "ebitda_pct": "−43%",  "pat": "−₹153 cr"},
            {"label": "Q4 FY26", "revenue": "₹348 cr", "ebitda": "−₹202 cr", "ebitda_pct": "−58%",  "pat": "−₹191 cr",  "note": "8th straight neg-EBITDA"},
        ],
        "signals": [
            {"date": "2024-09-14", "kind": "downgrade", "headline": "CARE downgrades BBB−/Negative → BB+/Stable", "detail": "Citing adverse litigation orders; contingent liabilities ₹685.61 cr (incl. ₹351 cr tax dispute).", "url": "https://www.careratings.com/upload/CompanyFiles/PR/202409140929_Omaxe_Limited.pdf"},
            {"date": "2025-05-15", "kind": "litigation", "headline": "Punjab RERA orders Omaxe New Chandigarh to pay statutory delay interest", "detail": "5+ year possession delay at 'The Lake' project.", "url": "https://www.tribuneindia.com/news/punjab/punjab-rera-directs-omaxe-to-pay-delay-interest-to-gurugram-couple-for-new-chandigarh-flat/"},
            {"date": "2025-07-07", "kind": "downgrade", "headline": "Infomerics reaffirms / refreshes rating action", "detail": "Cited margin pressure and inventory.", "url": "https://infomericstorage.blob.core.windows.net/uploads/pr_omaxe_7july25_3696fd248e.pdf"},
            {"date": "2025-09-15", "kind": "launch", "headline": "Ludhiana luxury launch announced (~₹1,060 cr GDV)", "detail": "Premium pivot from Tier-2/3 township base.", "url": "https://tradebrains.in/can-omaxes-1060-cr-premium-project-sell-out-strengthen-revenue-visibility-and-boost-growth/"},
            {"date": "2025-10-12", "kind": "downgrade", "headline": "CARE updates rating rationale Oct 2025", "url": "https://www.careratings.com/upload/CompanyFiles/PR/202510121051_Omaxe_Limited.pdf"},
            {"date": "2026-05-15", "kind": "concall", "headline": "Q4 FY26 board meeting — losses widen further", "detail": "Q4 consolidated loss ₹191.30 cr (+29% YoY); shareholder funds NEGATIVE −₹205 cr; current liabilities ₹13,953 cr.", "url": "https://www.marketsmojo.com/news/result-analysis/omaxe-q4-fy26-mounting-losses-deepen-as-operational-crisis-intensifies-3994692"},
        ],
        "sources": [
            {"url": "https://www.screener.in/company/OMAXE/consolidated/", "title": "Screener.in — Omaxe consolidated"},
            {"url": "https://trendlyne.com/fundamentals/financials/969/OMAXE/omaxe-ltd/", "title": "Trendlyne — Omaxe fundamentals"},
            {"url": "https://www.businessworld.in/article/omaxe-ends-fy25-with-rs-3000-cr-sales-eyes-growth-in-tier-2-tier-3-cities-563294", "title": "BW Businessworld — FY25 ₹3,000cr sales"},
            {"url": "https://www.marketsmojo.com/news/result-analysis/omaxe-q4-fy26-mounting-losses-deepen-as-operational-crisis-intensifies-3994692", "title": "MarketsMojo — Q4 FY26 analysis"},
            {"url": "https://www.livelaw.in/amp/consumer-cases/punjab-rera-directs-omaxe-chandigarh-extension-developers-to-pay-interest-to-homebuyer-for-delayed-possession-312012", "title": "LiveLaw — 5-yr possession delay"},
        ],
    },

    # ─────────────────────────────────────────────────────────────────
    "indiamart": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹325 cr", "ebitda": "₹110 cr",  "ebitda_pct": "33.8%", "pat": "₹148 cr"},
            {"label": "Q2 FY25", "revenue": "₹340 cr", "ebitda": "₹125 cr",  "ebitda_pct": "36.8%", "pat": "₹136 cr"},
            {"label": "Q3 FY25", "revenue": "₹354 cr", "ebitda": "₹131 cr",  "ebitda_pct": "37.0%", "pat": "₹121 cr"},
            {"label": "Q4 FY25", "revenue": "₹355 cr", "ebitda": "₹133 cr",  "ebitda_pct": "37.5%", "pat": "₹181 cr",  "note": "Peak PAT"},
            {"label": "Q1 FY26", "revenue": "₹372 cr", "ebitda": "₹130 cr",  "ebitda_pct": "34.9%", "pat": "₹140 cr"},
            {"label": "Q2 FY26", "revenue": "₹390 cr", "ebitda": "₹138 cr",  "ebitda_pct": "35.4%", "pat": "₹145 cr"},
            {"label": "Q3 FY26", "revenue": "₹405 cr", "ebitda": "₹145 cr",  "ebitda_pct": "35.8%", "pat": "₹138 cr"},
            {"label": "Q4 FY26", "revenue": "₹404 cr", "ebitda": "₹110 cr",  "ebitda_pct": "27.3%", "pat": "₹50.2 cr", "note": "−72% YoY; effective tax 35.97% vs 17.19%"},
        ],
        "signals": [
            {"date": "2025-09-30", "kind": "regulatory", "headline": "SEBI / accounting scrutiny on lifetime value disclosures", "detail": "Silver tier churn elevated post-price hike Q2 FY26."},
            {"date": "2026-01-20", "kind": "analyst", "headline": "Brokerages downgrade as supplier churn flagged", "detail": "Annual retention down 10–15%; Silver tier exits accelerating."},
            {"date": "2026-04-15", "kind": "other", "headline": "IndiaMART STOPS reporting traffic metrics", "detail": "Cites bot/agentic-traffic surge — transparency red flag.", "url": "https://www.medianama.com/2026/05/223-indiamart-q4fy26-agentic-traffic-stop-traffic-metrics/"},
            {"date": "2026-05-08", "kind": "concall", "headline": "Q4 FY26 — 1,200 paid suppliers LOST in the quarter", "detail": "Total paid base 220,000. Management SUSPENDS guidance on net additions.", "url": "https://inc42.com/buzz/indiamart-q4-net-profit-plunges-72-yoy-to-%E2%82%B950-cr/"},
            {"date": "2026-05-09", "kind": "analyst", "headline": "Stock −34% from 52-wk high after Q4 print", "url": "https://www.marketsmojo.com/news/result-analysis/indiamart-intermesh-q4-fy26-profit-plummets-72-despite-revenue-growth-3972254"},
        ],
        "sources": [
            {"url": "https://www.screener.in/company/INDIAMART/consolidated/", "title": "Screener.in"},
            {"url": "https://www.marketsmojo.com/news/result-analysis/indiamart-intermesh-q4-fy26-profit-plummets-72-despite-revenue-growth-3972254", "title": "MarketsMojo Q4 FY26"},
            {"url": "https://inc42.com/buzz/indiamart-q4-net-profit-plunges-72-yoy-to-%E2%82%B950-cr/", "title": "Inc42 — supplier base decline"},
            {"url": "https://www.whalesbook.com/corporate-news/English/tech/IndiaMART-Revenue-Surges-14percent-in-Q4-Amid-Supplier-Base-Decline/69fb49b1d27867b982d4800d", "title": "Whalesbook — supplier base"},
            {"url": "https://www.medianama.com/2026/05/223-indiamart-q4fy26-agentic-traffic-stop-traffic-metrics/", "title": "Medianama — stopped reporting traffic"},
        ],
    },

    # ─────────────────────────────────────────────────────────────────
    "bata-india": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹944 cr",  "ebitda": "₹220 cr", "ebitda_pct": "23.3%", "pat": "₹70 cr"},
            {"label": "Q2 FY25", "revenue": "₹792 cr",  "ebitda": "₹176 cr", "ebitda_pct": "22.2%", "pat": "₹35 cr"},
            {"label": "Q3 FY25", "revenue": "₹957 cr",  "ebitda": "₹202 cr", "ebitda_pct": "21.1%", "pat": "₹56 cr"},
            {"label": "Q4 FY25", "revenue": "₹788 cr",  "ebitda": "₹178 cr", "ebitda_pct": "22.6%", "pat": "₹45.9 cr"},
            {"label": "Q1 FY26", "revenue": "₹933 cr",  "ebitda": "₹197 cr", "ebitda_pct": "21.1%", "pat": "₹61 cr"},
            {"label": "Q2 FY26", "revenue": "₹808 cr",  "ebitda": "₹146 cr", "ebitda_pct": "18.1%", "pat": "₹14 cr",  "note": "Margin breakdown begins"},
            {"label": "Q3 FY26", "revenue": "₹947 cr",  "ebitda": "₹171 cr", "ebitda_pct": "18.1%", "pat": "₹15 cr",  "note": "PAT −73% YoY"},
            {"label": "Q4 FY26", "revenue": "₹827 cr",  "ebitda": "₹151 cr", "ebitda_pct": "18.2%", "pat": "₹2.21 cr", "note": "−95% YoY; gross margin 13.15% vs 21.04%"},
        ],
        "signals": [
            {"date": "2025-10-28", "kind": "analyst", "headline": "JM Financial cuts to REDUCE; cite volume −6% YoY", "detail": "Discount-led volume defence; ZBM rollout uneven.", "url": "https://www.businesstoday.in/markets/stocks/story/bata-india-shares-slump-7-post-weak-q2-results-jm-financial-cuts-rating-to-reduce-499800-2025-10-28"},
            {"date": "2026-03-04", "kind": "analyst", "headline": "Axis Securities downgrades to HOLD"},
            {"date": "2026-05-10", "kind": "analyst", "headline": "MarketsMojo flags SELL after Q4 reveal", "url": "https://www.marketsmojo.com/news/result-analysis/bata-india-q4-fy26-profit-plummets-95-as-margin-pressures-mount-4020839"},
            {"date": "2026-05-28", "kind": "concall", "headline": "Q4 FY26: gross margin collapses 789bps YoY", "detail": "21.04% → 13.15%; aggressive discounting to clear inventory; inventory cut 28% YoY to ₹660.1cr.", "url": "https://www.whalesbook.com/corporate-news/English/consumer-products/Bata-India-Q4-FY26-Revenue-Up-51percent-Amid-Margin-Pressure/6a1d3f098133c02995417f49"},
            {"date": "2026-06-03", "kind": "concall", "headline": "Mgmt: US reciprocal-tariff drag = 110bps adj-EBITDA in 9M FY26", "detail": "ZBM expansion to 700+ doors with +6.1% volume; non-ZBM doors negative."},
        ],
        "sources": [
            {"url": "https://www.marketsmojo.com/news/result-analysis/bata-india-q4-fy26-profit-plummets-95-as-margin-pressures-mount-4020839", "title": "MarketsMojo Q4 FY26"},
            {"url": "https://www.whalesbook.com/corporate-news/English/consumer-products/Bata-India-Q4-FY26-Revenue-Up-51percent-Amid-Margin-Pressure/6a1d3f098133c02995417f49", "title": "Whalesbook Q4 FY26"},
            {"url": "https://www.ibtimes.co.in/bata-india-q4-profit-slumps-95-pc-due-one-time-loss-902399", "title": "IBTimes — 95% PAT slump"},
            {"url": "https://www.businesstoday.in/markets/stocks/story/bata-india-shares-slump-7-post-weak-q2-results-jm-financial-cuts-rating-to-reduce-499800-2025-10-28", "title": "JM Financial Q2 downgrade"},
            {"url": "https://www.marketsmojo.com/news/result-analysis/bata-india-q3-fy26-profit-plunges-73-as-margin-pressures-mount-3829400", "title": "MarketsMojo Q3 FY26"},
        ],
    },

    # ─────────────────────────────────────────────────────────────────
    "religare": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹1,856 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "₹181 cr",  "note": "One-off gain (MTM / tax reversal)"},
            {"label": "Q2 FY25", "revenue": "₹1,710 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "₹27 cr"},
            {"label": "Q3 FY25", "revenue": "₹1,952 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "₹69 cr",   "note": "RBI CAP on RFL lifted Jul-25"},
            {"label": "Q4 FY25", "revenue": "₹1,668 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "−₹63 cr",  "note": "Care Health commission spike + transition costs"},
            {"label": "Q1 FY26", "revenue": "₹2,042 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "₹151 cr",  "note": "Investment gains / MTM positive"},
            {"label": "Q2 FY26", "revenue": "₹1,861 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "₹8 cr",    "note": "Care commission > premium growth"},
            {"label": "Q3 FY26", "revenue": "₹2,077 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "₹46 cr"},
            {"label": "Q4 FY26", "revenue": "₹2,473 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "₹96 cr",   "note": "Demerger approved; ₹750cr Burman infusion; PAT > full-year"},
        ],
        "signals": [
            {"date": "2024-10-15", "kind": "other", "headline": "Burman family open-offer crosses control threshold", "detail": "Singh-era promoter group exits."},
            {"date": "2025-07-10", "kind": "regulatory", "headline": "RBI CAP on Religare Finvest lifted", "detail": "Restart of secured MSME lending."},
            {"date": "2026-02-15", "kind": "other", "headline": "Burman Group infuses ₹750 cr capital", "url": "https://www.whalesbook.com/corporate-news/English/bankingfinance/Religare-Enterprises-FY26-Demerger-plan-gains-traction-Burman-Group-infuses-indian-rupee750-Cr/6a0b46b9cfe07c0307ebac00"},
            {"date": "2026-05-12", "kind": "concall", "headline": "Q4 FY26: Demerger of 3 businesses APPROVED", "detail": "Care Health, Finvest, Broking each demerged. Care Health → standalone listing prep over 12 months.", "url": "https://cdn.prod.website-files.com/66ab5208ecc61810760ef8d7/6a03629b51d2ccbe3203baea_REL_Q4_and_FY26_Investor_Presentation_12_May.pdf"},
            {"date": "2026-05-13", "kind": "concall", "headline": "Care Health H1 FY26 operating loss ₹70 cr — claims +21% vs premium +8%", "detail": "Commission outgo ₹627 cr + opex ₹573 cr.", "url": "https://unlistedzone.com/h1-fy26-shows-care-health-is-growing-but-its-claims-are-growing-faster"},
        ],
        "sources": [
            {"url": "https://tradebrains.in/religare-enterprises-fy26-revenue-hits-8494-cr-as-finvest-pat-surges-480/", "title": "Tradebrains — FY26 ₹8,494cr revenue, PAT plunges"},
            {"url": "https://www.investywise.com/religare-enterprises-limited-q4-and-fy26-earnings-call-transcript/", "title": "Investywise — Q4 FY26 earnings call"},
            {"url": "https://www.freepressjournal.in/business/religare-enterprises-q4-profit-drops-37-to-957-crore-despite-21-revenue-growth", "title": "FPJ — Q4 PAT −37%"},
            {"url": "https://www.newsdrum.in/business/religare-enterprises-q4-profit-drops-37-pc-to-rs-96-crore-11830025", "title": "NewsDrum — Q4 PAT ₹96cr"},
            {"url": "https://www.screener.in/company/RELIGARE/consolidated/", "title": "Screener.in — Religare consolidated"},
            {"url": "https://irdai.gov.in/health-insurance-products", "title": "IRDAI public disclosures (health)"},
        ],
    },

    # ─────────────────────────────────────────────────────────────────
    "ht-media": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹427 cr", "ebitda": "₹7 cr",  "ebitda_pct": "~2%",   "pat": "−₹20 cr"},
            {"label": "Q2 FY25", "revenue": "₹479 cr", "ebitda": "₹33 cr", "ebitda_pct": "7%",    "pat": "−₹6 cr"},
            {"label": "Q3 FY25", "revenue": "₹540 cr", "ebitda": "₹46 cr", "ebitda_pct": "~9%",   "pat": "−₹2 cr"},
            {"label": "Q4 FY25", "revenue": "₹514 cr", "ebitda": "₹48 cr", "ebitda_pct": "~9%",   "pat": "₹58 cr",  "note": "PBT ₹54 cr"},
            {"label": "Q1 FY26", "revenue": "₹451 cr", "ebitda": "₹13 cr", "ebitda_pct": "~3%",   "pat": "−₹11 cr", "note": "Standalone Q1 loss ₹28.17cr"},
            {"label": "Q2 FY26", "revenue": "₹499 cr", "ebitda": "₹44 cr", "ebitda_pct": "9-11%", "pat": "−₹4 cr"},
            {"label": "Q3 FY26", "revenue": "₹532 cr", "ebitda": "₹51 cr", "ebitda_pct": "10%",   "pat": "₹17 cr"},
            {"label": "Q4 FY26", "revenue": "₹558 cr", "ebitda": "—",      "ebitda_pct": "—",     "pat": "₹96 cr",  "note": "+15% YoY"},
        ],
        "signals": [
            {"date": "2025-08-30", "kind": "concall", "headline": "FY25 returns to profit on cost discipline", "url": "https://www.exchange4media.com/media-print-news/ht-media-returns-to-profit-in-fy25-147050.html"},
            {"date": "2026-03-31", "kind": "shutdown", "headline": "OTTplay discontinued effective Mar 31, 2026", "detail": "Discontinued ops loss ₹100.96 cr on ₹96.64 cr income — losing nearly ₹1 per ₹1 earned."},
            {"date": "2026-05-15", "kind": "concall", "headline": "Q4 FY26 print ad revenue +8% to ₹1,148 cr; circulation −2% to ₹208 cr", "url": "https://bestmediainfo.com/mediainfo/mediainfo-marketing/ht-media-fy26-print-ad-revenue-rises-8-to-rs-1148-cr-circulation-slips-2-to-rs-208-cr-11886722"},
            {"date": "2026-05-20", "kind": "shutdown", "headline": "HT Media surrenders 4 metro FM radio licenses", "detail": "Radio Nasha 91.9 (Mumbai), Radio One 94.3 (Delhi/Mum/Blr), Fever 91.9 (Chennai). Effective Jun 15, 2026. FY25 radio turnover ₹29.19 cr against negative net worth −₹172 cr (10.33% of consolidated).", "url": "https://www.whalesbook.com/corporate-news/English/media-and-entertainment/HT-Media-Exits-Metro-Radio-as-Losses-Outweigh-indian-rupee29-Cr-Turnover/6a07037ee125a601ebdb3cd1"},
            {"date": "2026-05-25", "kind": "analyst", "headline": "MarketsMojo flags 'profit swing masks deeper operational challenges'", "url": "https://www.marketsmojo.com/news/result-analysis/h-t-media-q4-fy26-profit-swing-masks-deeper-operational-challenges-4023639"},
        ],
        "sources": [
            {"url": "https://bestmediainfo.com/mediainfo/mediainfo-marketing/ht-media-fy26-print-ad-revenue-rises-8-to-rs-1148-cr-circulation-slips-2-to-rs-208-cr-11886722", "title": "Best Media Info — FY26 print ad/circulation"},
            {"url": "https://www.whalesbook.com/corporate-news/English/media-and-entertainment/HT-Media-Exits-Metro-Radio-as-Losses-Outweigh-indian-rupee29-Cr-Turnover/6a07037ee125a601ebdb3cd1", "title": "Whalesbook — Metro Radio exit"},
            {"url": "https://www.prysm.fi/news/ht-media-q3-fy26-stable-revenue-10-ebitda-margin-945-cr-net-cash", "title": "Prysm — Q3 ₹945cr net cash"},
            {"url": "https://www.marketsmojo.com/news/result-analysis/h-t-media-q4-fy26-profit-swing-masks-deeper-operational-challenges-4023639", "title": "MarketsMojo Q4 FY26"},
            {"url": "https://www.adgully.com/we-plan-to-go-behind-a-paywall-with-mint-other-properties-over-time-rajiv-bansal-83511.html", "title": "Adgully — Mint paywall strategy"},
            {"url": "https://trendlyne.com/fundamentals/financials/575/HTMEDIA/ht-media-ltd/", "title": "Trendlyne — HT Media"},
        ],
    },

    # ─────────────────────────────────────────────────────────────────
    "spicejet": {
        "quarterly": [
            {"label": "Q3 FY24", "revenue": "₹2,157 cr", "ebitda": "~₹3 cr",   "ebitda_pct": "~0%",  "pat": "−₹299 cr", "note": "Lessor / forex drag"},
            {"label": "Q4 FY24", "revenue": "₹1,719 cr", "ebitda": "₹310 cr",  "ebitda_pct": "~18%", "pat": "+₹120 cr", "note": "Festive yield"},
            {"label": "Q1 FY25", "revenue": "₹1,646 cr", "ebitda": "₹401 cr",  "ebitda_pct": "~24%", "pat": "+₹159 cr", "note": "Peak PLF 91%"},
            {"label": "Q2 FY25", "revenue": "₹915 cr",   "ebitda": "−₹59 cr",  "ebitda_pct": "neg",  "pat": "−₹458 cr", "note": "Fleet shrink begins"},
            {"label": "Q3 FY25", "revenue": "₹1,141 cr", "ebitda": "₹210 cr",  "ebitda_pct": "~18%", "pat": "+₹26 cr",  "note": "Post-QIP boost; net worth positive"},
            {"label": "Q4 FY25", "revenue": "₹1,446 cr", "ebitda": "—",        "ebitda_pct": "—",    "pat": "+₹325 cr", "note": "First full-yr PAT in 7 yrs; ATF −33%"},
            {"label": "Q1 FY26", "revenue": "₹1,106 cr", "ebitda": "−₹18 cr",  "ebitda_pct": "~−2%", "pat": "−₹234 cr", "note": "India-Pak airspace closure"},
            {"label": "Q2 FY26", "revenue": "₹708 cr",   "ebitda": "−₹204 cr", "ebitda_pct": "neg",  "pat": "−₹621 cr", "note": "₹120cr grounded-fleet cost; FX recalibration"},
        ],
        "signals": [
            {"date": "2024-09-21", "kind": "other", "headline": "₹3,000 cr QIP @ ₹61.6/share", "detail": "Ajay Singh cut from 47.8% → 30-35%.", "url": "https://www.business-standard.com/companies/news/spicejet-raises-rs-3-000-cr-from-institutional-investors-via-share-sale-124092100773_1.html"},
            {"date": "2024-10-15", "kind": "regulatory", "headline": "DGCA filing: needs ₹400cr over 24 months for return-to-service", "url": "https://www.business-standard.com/companies/news/will-back-grounded-planes-to-service-in-24-months-spicejet-to-dgca-124101500487_1.html"},
            {"date": "2024-10-14", "kind": "litigation", "headline": "New insolvency case filed — ₹58 cr lessor dues", "url": "https://www.business-standard.com/companies/news/spicejet-faces-new-insolvency-case-over-rs-58-crore-unpaid-dues-to-lessor-124101400644_1.html"},
            {"date": "2025-03-15", "kind": "other", "headline": "Promoter funding ₹294 cr — stake to 33.47%"},
            {"date": "2026-04-10", "kind": "other", "headline": "6-month employee furlough Apr-Sep 2026 announced", "detail": "Salary payments delayed.", "url": "https://marksmendaily.com/business/spicejet-delays-salaries-amid-financial-turbulence/"},
            {"date": "2026-04-15", "kind": "other", "headline": "Only 13 of 68 aircraft active; 19 engines globally for maintenance"},
            {"date": "2026-02-20", "kind": "analyst", "headline": "Auditor flags going-concern: accumulated losses >₹8,900cr", "url": "https://www.whalesbook.com/news/English/transportation/SpiceJets-Foreign-Crew-Symptom-of-Costly-ACMI-and-Slot-Survival/698e12ce19b91b06433d562f"},
        ],
        "sources": [
            {"url": "https://www.business-standard.com/companies/quarterly-results/spicejet-q2-fy26-results-loss-widens-to-621-crore-revenue-dips-13-125111201154_1.html", "title": "Business Standard — Q2 FY26"},
            {"url": "https://www.businessworld.in/article/spicejet-reports-rs-23385-cr-net-loss-in-q1-fy26-revenue-down-by-348-570358", "title": "BW Businessworld — Q1 FY26"},
            {"url": "https://www.business-standard.com/companies/quarterly-results/spicejet-q4fy25-results-pat-jumps-nearly-three-fold-to-rs-325-crore-125061400245_1.html", "title": "Business Standard — Q4 FY25"},
            {"url": "https://www.multibagg.ai/deep-dive/blogs/92132-spicejet-q3fy26-results_SPICEJET_Q3_FY26_MBEQU3174", "title": "Multibagg — Q3 FY26 RASK/ancillary"},
            {"url": "https://www.screener.in/company/SPICEJET/", "title": "Screener.in — SpiceJet"},
            {"url": "https://corporate.spicejet.com/investorsfinancialinformation.aspx", "title": "SpiceJet investor relations"},
        ],
    },

    # ──── P2 Tier — added 2026-06-08 from 16-agent parallel fan-out ────

    "igl": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹3,891 cr", "ebitda": "₹581 cr", "ebitda_pct": "14.9%", "pat": "₹401 cr", "note": "PAT −8.6% YoY on higher gas purchase costs"},
            {"label": "Q2 FY25", "revenue": "₹4,070 cr", "ebitda": "₹536 cr", "ebitda_pct": "13.2%", "pat": "₹431 cr", "note": "Record sales volume; margins pressured by input costs"},
            {"label": "Q3 FY25", "revenue": "₹3,759 cr", "ebitda": "₹364 cr", "ebitda_pct": "9.7%",  "pat": "₹286 cr", "note": "First full quarter of APM cut impact; margin collapse"},
            {"label": "Q4 FY25", "revenue": "₹3,950 cr", "ebitda": "₹497 cr", "ebitda_pct": "12.6%", "pat": "₹349 cr", "note": "Highest-ever 9.18 mmscmd sales volume; PAT −9% YoY"},
            {"label": "Q1 FY26", "revenue": "₹4,327 cr", "ebitda": "₹512 cr", "ebitda_pct": "11.8%", "pat": "₹356 cr", "note": "LNG volumes −56%; PAT −11% YoY"},
            {"label": "Q2 FY26", "revenue": "₹4,022 cr", "ebitda": "₹442 cr", "ebitda_pct": "11.0%", "pat": "₹372 cr", "note": "EBITDA −13.6% QoQ on sourcing mix shift"},
            {"label": "Q3 FY26", "revenue": "₹4,073 cr", "ebitda": "₹489 cr", "ebitda_pct": "12.0%", "pat": "₹359 cr", "note": "PAT +25% YoY; EBITDA +31%; ₹3.25 interim dividend"},
            {"label": "Q4 FY26", "revenue": "₹4,584 cr", "ebitda": "₹423 cr", "ebitda_pct": "9.2%",  "pat": "₹277 cr", "note": "PAT −21% YoY; EBITDA ₹4.85/SCM"},
        ],
        "signals": [
            {"date": "2024-10-16", "kind": "regulatory", "headline": "Govt cuts APM gas allocation to CGDs by ~20%", "detail": "Cheaper APM gas ($6.5/mmbtu) for CNG business reduced ~20% effective Oct 16, 2024", "url": "https://www.equentis.com/blog/mgl-igl-fall-20-on-fresh-apm-gas-allocation-cuts/"},
            {"date": "2024-11-18", "kind": "regulatory", "headline": "Second APM allocation cut — IGL, MGL shares plunge up to 20%", "detail": "Cumulative ~40% cut in two months; APM share 51% → 34%", "url": "https://www.business-standard.com/markets/news/mgl-igl-plunge-up-to-20-on-further-reduction-in-domestic-gas-allocation-124111800191_1.html"},
            {"date": "2025-04-28", "kind": "concall", "headline": "Q4 FY25 earnings call — record sales volume 9.18 mmscmd", "detail": "PAT ₹349 cr (−9% YoY); management flags structural APM headwind", "url": "https://www.iglonline.net/uploads/announcement/Transcript%20of%20Q4%20Earning%20Call%20-%20April%2028,%202025.pdf"},
            {"date": "2025-05-15", "kind": "regulatory", "headline": "Delhi draft EV Policy 2.0 — no new CNG auto registrations from Aug 15, 2025", "detail": "All DTC/DIMTS buses to be electric; IGL share dips >4% intraday", "url": "https://www.angelone.in/news/share-market/delhi-ev-policy-20-triggers-over-4-fall-in-igl-share-price"},
            {"date": "2025-07-28", "kind": "concall", "headline": "Q1 FY26 results — PAT −11% YoY, LNG volumes −56%"},
            {"date": "2026-01-30", "kind": "concall", "headline": "Q3 FY26: PAT +25% YoY to ₹358 cr; ₹3.25 interim dividend"},
            {"date": "2026-05-20", "kind": "concall", "headline": "Q4 FY26: PAT −21% YoY, margin compresses to 9.2%", "detail": "Revenue ₹4,584 cr (+6%); FY26 PAT ₹1,364 cr (−7%)", "url": "https://www.businesstoday.in/markets/stocks/story/igl-shares-where-the-stock-is-headed-post-q4-results-check-target-prices-532413-2026-05-20"},
        ],
        "sources": [
            {"url": "https://www.screener.in/company/IGL/consolidated/", "title": "Screener — Indraprastha Gas Ltd consolidated"},
            {"url": "https://www.business-standard.com/markets/news/mgl-igl-plunge-up-to-20-on-further-reduction-in-domestic-gas-allocation-124111800191_1.html", "title": "Business Standard — APM allocation cut Nov 2024"},
            {"url": "https://www.marketsmojo.com/news/result-analysis/indraprastha-gas-q4-fy26-margin-pressure-overshadows-revenue-growth-3999065", "title": "MarketsMojo — IGL Q4 FY26"},
            {"url": "https://www.iglonline.net/financial", "title": "IGL Investor Relations"},
            {"url": "https://www.iglonline.net/uploads/announcement/Transcript%20of%20Q4%20Earning%20Call%20-%20April%2028,%202025.pdf", "title": "IGL Q4 FY25 concall transcript"},
            {"url": "https://www.businesstoday.in/markets/stocks/story/igl-shares-where-the-stock-is-headed-post-q4-results-check-target-prices-532413-2026-05-20", "title": "Business Today — IGL post-Q4 FY26 targets"},
        ],
    },

    "tv-today": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹245.93 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "₹37.94 cr", "note": "Lok Sabha elections boost"},
            {"label": "Q2 FY25", "revenue": "₹206.77 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "₹8.35 cr"},
            {"label": "Q3 FY25", "revenue": "₹243.07 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "₹8.82 cr"},
            {"label": "Q4 FY25", "revenue": "₹249.17 cr", "ebitda": "₹16.32 cr", "ebitda_pct": "6.5%", "pat": "₹6.15 cr"},
            {"label": "Q1 FY26", "revenue": "₹198.44 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "₹7.32 cr"},
            {"label": "Q2 FY26", "revenue": "₹187.55 cr", "ebitda": "neg", "ebitda_pct": "neg", "pat": "−₹2.04 cr", "note": "First loss quarter; ₹17.61 cr radio impairment"},
            {"label": "Q3 FY26", "revenue": "₹209.24 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "−₹0.56 cr [unverified]"},
            {"label": "Q4 FY26", "revenue": "₹213.47 cr", "ebitda": "₹4.57 cr", "ebitda_pct": "2.14%", "pat": "₹9.02 cr", "note": "PAT +46.7% YoY off depressed base"},
        ],
        "signals": [
            {"date": "2025-09-09", "kind": "shutdown", "headline": "Creative Channel walks away from Ishq FM acquisition", "detail": "CCAMPL terminates ₹20 cr MoU; TV Today forfeits ₹10 cr advance.", "url": "https://www.storyboard18.com/how-it-works/ishq-fm-sale-collapses-as-tv-today-network-terminates-deal-with-ccampl-80711.htm"},
            {"date": "2025-11-13", "kind": "concall", "headline": "Q2 FY26: TV Today swings to first-ever net loss ₹2.04 cr", "detail": "Revenue −9.3% YoY to ₹187.55 cr; ₹17.61 cr radio impairment", "url": "https://www.exchange4media.com/media-tv-news/q2-fy26-tv-today-network-reports-net-loss-of-rs-204-crore-149277.html"},
            {"date": "2025-11-14", "kind": "analyst", "headline": "MarketsMojo flags operating-margin collapse on Q2 FY26", "url": "https://www.marketsmojo.com/news/result-analysis/tv-today-network-q2-fy26-steep-loss-raises-alarm-as-operating-margins-collapse-3692702"},
            {"date": "2026-02-19", "kind": "launch", "headline": "TV Today signs ₹10 cr MoU with Abhijit Realtors for Ishq 104.8 FM", "detail": "Half the original CCAMPL valuation.", "url": "https://bestmediainfo.com/mediainfo/mediainfo-radio/tv-today-signs-rs-10-crore-deal-to-sell-1048-fm-radio-business-to-abhijit-realtors-10813065"},
            {"date": "2026-03-04", "kind": "regulatory", "headline": "I&B Ministry orders BARC to freeze news-genre TRPs for 4 weeks", "detail": "Directly affects Aaj Tak / India Today ad pricing.", "url": "https://marketingmind.in/ib-ministry-directs-barc-to-suspend-tv-news-trp-reporting-for-four-weeks/"},
            {"date": "2026-05-15", "kind": "concall", "headline": "FY26 PAT collapses 82% YoY to ₹13.74 cr; revenue −18.6% to ₹808.70 cr", "url": "https://scanx.trade/stock-market-news/companies/tv-today-network-reports-audited-financial-results-for-quarter-and-year-ended-march-31-2026/40390201"},
            {"date": "2026-05-16", "kind": "analyst", "headline": "MarketsMojo: revenue decline and institutional exit", "url": "https://www.marketsmojo.com/news/result-analysis/tv-today-network-q4-fy26-profitability-returns-amid-revenue-decline-and-institutional-exit-3993456"},
        ],
        "sources": [
            {"url": "https://www.screener.in/company/TVTODAY/consolidated/", "title": "TV Today — Screener consolidated"},
            {"url": "https://trendlyne.com/fundamentals/financials/1432/TVTODAY/tv-today-network-ltd/", "title": "Trendlyne — TV Today"},
            {"url": "https://www.exchange4media.com/media-tv-news/q2-fy26-tv-today-network-reports-net-loss-of-rs-204-crore-149277.html", "title": "Exchange4media — Q2 FY26 first loss"},
            {"url": "https://bestmediainfo.com/mediainfo/television/tv-today-revenue-dips-93-to-rs-18755-crore-in-q2-fy26-10649346", "title": "Best Media Info — Q2 FY26"},
            {"url": "https://www.storyboard18.com/how-it-works/ishq-fm-sale-collapses-as-tv-today-network-terminates-deal-with-ccampl-80711.htm", "title": "Storyboard18 — Ishq FM sale collapse"},
            {"url": "https://marketingmind.in/ib-ministry-directs-barc-to-suspend-tv-news-trp-reporting-for-four-weeks/", "title": "Marketing Mind — BARC TRP freeze"},
        ],
    },

    "jbm-auto": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹1,144 cr", "ebitda": "₹149 cr", "ebitda_pct": "13.0%", "pat": "₹33 cr"},
            {"label": "Q2 FY25", "revenue": "₹1,286 cr", "ebitda": "₹175 cr", "ebitda_pct": "13.6%", "pat": "₹49 cr"},
            {"label": "Q3 FY25", "revenue": "₹1,414 cr", "ebitda": "₹197 cr", "ebitda_pct": "13.9%", "pat": "₹56 cr"},
            {"label": "Q4 FY25", "revenue": "₹1,646 cr", "ebitda": "₹197 cr", "ebitda_pct": "12.0%", "pat": "₹72 cr"},
            {"label": "Q1 FY26", "revenue": "₹1,254 cr", "ebitda": "₹180 cr", "ebitda_pct": "14.3%", "pat": "₹37 cr", "note": "OEM segment +35.9% YoY"},
            {"label": "Q2 FY26", "revenue": "₹1,368 cr", "ebitda": "₹195 cr", "ebitda_pct": "14.2%", "pat": "₹52 cr", "note": "Revenue +6.4% YoY trails 5-yr CAGR ~29%"},
            {"label": "Q3 FY26", "revenue": "₹1,614 cr", "ebitda": "₹202 cr", "ebitda_pct": "12.5%", "pat": "₹55 cr", "note": "Margin erosion despite +18% QoQ revenue"},
            {"label": "Q4 FY26", "revenue": "₹1,852 cr", "ebitda": "₹236 cr", "ebitda_pct": "12.7%", "pat": "₹84 cr", "note": "Interest +46.6% QoQ to ₹108 cr"},
        ],
        "signals": [
            {"date": "2025-08-11", "kind": "launch", "headline": "PM e-Bus Sewa-2: 1,021 e-bus order win (Gujarat, Maharashtra, Haryana)", "detail": "~₹5,500 cr order under GoI's PM e-Bus Sewa Scheme-2"},
            {"date": "2025-10-31", "kind": "concall", "headline": "Q2 FY26: Revenue growth slows to 6.4% YoY", "detail": "5-yr CAGR ~29%; analysts flag margin pressure"},
            {"date": "2026-01-31", "kind": "concall", "headline": "Q3 FY26: Margin erosion concern despite +18% QoQ revenue"},
            {"date": "2026-04-22", "kind": "launch", "headline": "Haryana CM flags off first batch of JBM ECOLIFE e-buses at Panipat depot"},
            {"date": "2026-04-30", "kind": "other", "headline": "FY26 results board meeting rescheduled to May 11, 2026"},
            {"date": "2026-05-11", "kind": "concall", "headline": "Q4 FY26: interest +46.6% QoQ to ₹108 cr; borrowings ₹2,070 cr; D/E 2.24x"},
            {"date": "2026-05-11", "kind": "concall", "headline": "Trade receivables double to ₹2,185 cr (36% of assets); OCF −59.4%"},
            {"date": "2026-06-03", "kind": "other", "headline": "May 2026: 49% market share in India e-bus registrations"},
        ],
        "sources": [
            {"url": "https://www.marketsmojo.com/news/result-analysis/jbm-auto-q4-fy26-strong-profit-surge-masks-rising-interest-burden-3987525", "title": "MarketsMojo — JBM Q4 FY26"},
            {"url": "https://scanx.trade/stock-market-news/companies/jbm-auto-reports-fy26-audited-results-consolidated-revenue-at-6-088-37-crores-net-profit-at-238-07-crores/40060535", "title": "Scanx — JBM FY26 audited"},
            {"url": "https://www.whalesbook.com/news/English/industrial-goodsservices/JBM-Auto-Revenue-Jumps-on-EVs-But-Rising-Debt-and-Weak-Cash-Flow-Signal-Trouble/6a04086a9444064ed0f43d9b", "title": "Whalesbook — debt + cash flow trouble"},
            {"url": "https://trendlyne.com/fundamentals/financials/667/JBMA/jbm-auto-ltd/", "title": "Trendlyne — JBM Auto"},
            {"url": "https://www.screener.in/company/JBMA/consolidated/", "title": "Screener — JBM Auto consolidated"},
            {"url": "https://www.autocarpro.in/news/jbm-auto-rolls-out-ecolife-electric-buses-in-haryana-118894", "title": "Autocar Professional — ECOLIFE Haryana"},
        ],
    },

    "hindware": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹599.91 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "−₹3.91 cr"},
            {"label": "Q2 FY25", "revenue": "₹639.63 cr", "ebitda": "₹38.49 cr", "ebitda_pct": "6%", "pat": "−₹12.06 cr"},
            {"label": "Q3 FY25", "revenue": "₹602.31 cr", "ebitda": "₹36.51 cr", "ebitda_pct": "6%", "pat": "−₹12.66 cr"},
            {"label": "Q4 FY25", "revenue": "₹699 cr", "ebitda": "₹51 cr", "ebitda_pct": "7%", "pat": "−₹31 cr", "note": "Bathware ₹360 cr / Pipes ₹247 cr / Consumer ₹92 cr"},
            {"label": "Q1 FY26", "revenue": "₹531 cr", "ebitda": "₹58 cr", "ebitda_pct": "11%", "pat": "—", "note": "Bathware ₹341 cr; Consumer ₹71 cr [unverified PAT]"},
            {"label": "Q2 FY26", "revenue": "₹676 cr", "ebitda": "₹60 cr", "ebitda_pct": "9%", "pat": "—", "note": "PBT ₹14 cr"},
            {"label": "Q3 FY26", "revenue": "₹640.08 cr", "ebitda": "₹51.57 cr", "ebitda_pct": "8%", "pat": "₹4.81 cr", "note": "Turnaround vs −₹11.88 cr Q3 FY25"},
            {"label": "Q4 FY26", "revenue": "₹663 cr", "ebitda": "₹63 cr", "ebitda_pct": "9%", "pat": "−₹19 cr", "note": "PBT ₹15 cr"},
        ],
        "signals": [
            {"date": "2025-03-27", "kind": "other", "headline": "Board approves Composite Scheme of Arrangement — demerger of Consumer Products into HHIL Ltd"},
            {"date": "2025-04-15", "kind": "downgrade", "headline": "CARE downgrades long-term to CARE BBB+ (from A-)", "detail": "Rating Watch with Developing Implications on ₹269 cr facilities", "url": "https://www.careratings.com/upload/CompanyFiles/PR/202504150406_Hindware_Home_Innovation_Limited.pdf"},
            {"date": "2025-08-12", "kind": "shutdown", "headline": "Board approves discontinuation of loss-making categories — air coolers, ceiling fans, air purifiers, water purifiers, furniture fittings"},
            {"date": "2026-03-07", "kind": "regulatory", "headline": "NCLT Kolkata-directed shareholder + creditor meetings for Composite Scheme of Arrangement", "url": "https://www.hindwarehomes.com/pdf/Proceedings_of_NCLT_convened_Meetings_07032026.pdf"},
            {"date": "2026-05-19", "kind": "concall", "headline": "FY26 audit flags going concern of EVOK Homes — liabilities exceed assets by ₹5.55 cr"},
            {"date": "2026-05-19", "kind": "concall", "headline": "FY26 consol net loss ₹39.31 cr; standalone net loss ₹70.7 cr; Pipes PBT loss ₹29 cr", "url": "https://www.whalesbook.com/corporate-news/English/consumer-products/Hindware-Home-Innovation-Reports-indian-rupee6877-Cr-Net-Loss-on-indian-rupee2510-Cr-Revenue-for-FY26/6a0c630403507e8ca6eda499"},
        ],
        "sources": [
            {"url": "https://www.screener.in/company/HINDWAREAP/consolidated/", "title": "Screener — Hindware Home Innovation"},
            {"url": "https://trendlyne.com/fundamentals/financials/178605/HINDWAREAP/hindware-home-innovation-ltd/", "title": "Trendlyne — Quarterly results"},
            {"url": "https://alphastreet.com/india/hindware-home-innovation-ltd-hindwareap-q4-2026-earnings-call-transcript/", "title": "AlphaStreet — Q4 FY26 concall transcript"},
            {"url": "https://www.whalesbook.com/corporate-news/English/consumer-products/Hindware-Home-Innovation-Reports-indian-rupee6877-Cr-Net-Loss-on-indian-rupee2510-Cr-Revenue-for-FY26/6a0c630403507e8ca6eda499", "title": "Whalesbook — FY26 loss"},
            {"url": "https://www.careratings.com/upload/CompanyFiles/PR/202504150406_Hindware_Home_Innovation_Limited.pdf", "title": "CARE Ratings — Apr 2025"},
            {"url": "https://www.sahi.com/news/hindware-home-innovation-q4-loss-shrinks-38-to-19-cr-despite-662-cr-revenue-low-4683-PE1_COR", "title": "Sahi.com — Q4 loss"},
        ],
    },

    "devyani": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹1,222 cr", "ebitda": "₹224 cr", "ebitda_pct": "18.3%", "pat": "₹22 cr"},
            {"label": "Q2 FY25", "revenue": "₹1,222 cr", "ebitda": "₹200 cr", "ebitda_pct": "16.3%", "pat": "−₹5 cr", "note": "Revenue +49% YoY; margin compression begins"},
            {"label": "Q3 FY25", "revenue": "₹1,302 cr", "ebitda": "₹220 cr", "ebitda_pct": "16.9%", "pat": "−₹7 cr"},
            {"label": "Q4 FY25", "revenue": "₹1,213 cr", "ebitda": "₹201 cr", "ebitda_pct": "16.6%", "pat": "−₹15 cr", "note": "FY25 full-year PAT ₹6.9 cr profit"},
            {"label": "Q1 FY26", "revenue": "₹1,357 cr", "ebitda": "₹207 cr", "ebitda_pct": "15.3%", "pat": "₹2.2 cr", "note": "KFC India +10.5%, Pizza Hut +3%"},
            {"label": "Q2 FY26", "revenue": "₹1,377 cr", "ebitda": "₹194 cr", "ebitda_pct": "14.1%", "pat": "−₹24 cr", "note": "EBITDA −2.2% YoY; margin slipped 220 bps"},
            {"label": "Q3 FY26", "revenue": "₹1,441 cr", "ebitda": "₹227 cr", "ebitda_pct": "15.7%", "pat": "−₹10 cr", "note": "Sky Gate hit EBITDA breakeven"},
            {"label": "Q4 FY26", "revenue": "₹1,437 cr", "ebitda": "₹230 cr", "ebitda_pct": "16.0%", "pat": "−₹10 cr", "note": "KFC SSSG +4.9% (best in 14Q); Pizza Hut India −3.5% YoY"},
        ],
        "signals": [
            {"date": "2026-04-24", "kind": "other", "headline": "Acquires 80.72% stake in Sky Gate Hospitality for ₹419.6 cr"},
            {"date": "2026-01-01", "kind": "other", "headline": "Board approves shift of registered office from Delhi to Haryana"},
            {"date": "2026-02-09", "kind": "other", "headline": "Shareholders approve registered office relocation to Gurugram"},
            {"date": "2026-04-06", "kind": "other", "headline": "Registered office relocation to Plot 18, Sector 35, Gurugram effective; CIN updated"},
            {"date": "2026-05-15", "kind": "concall", "headline": "Q4 + FY26 results: net loss ₹42.5 cr (vs +₹6.9 cr FY25); D/E at 2.17x", "url": "https://www.storyboard18.com/brand-marketing/devyani-international-loss-widens-despite-strong-kfc-led-revenue-growth-ws-l-98243.htm"},
            {"date": "2026-05-15", "kind": "shutdown", "headline": "FREEZE on new Pizza Hut openings for CY2026", "detail": "Pizza Hut store adds collapsed 63 → 9; shutting loss-making outlets.", "url": "https://www.storyboard18.com/brand-marketing/devyani-international-stops-pizza-hut-expansion-focuses-on-kfc-growth-ws-l-98530.htm"},
            {"date": "2026-05-15", "kind": "other", "headline": "FY27 guidance: 200-225 net new store adds; Sapphire Foods merger to close by year-end"},
            {"date": "2026-05-16", "kind": "analyst", "headline": "Stock tumbles 32% post-results on doubling borrowings and widening loss"},
        ],
        "sources": [
            {"url": "https://univest.in/blogs/devyani-international-q4-fy26-results-revenue-net-loss", "title": "Univest — Devyani Q4 FY26"},
            {"url": "https://www.marketsmojo.com/news/result-analysis/devyani-international-q4-fy26-mounting-losses-overshadow-revenue-growth-3993426", "title": "MarketsMojo — Devyani Q4 FY26"},
            {"url": "https://www.storyboard18.com/brand-marketing/devyani-international-loss-widens-despite-strong-kfc-led-revenue-growth-ws-l-98243.htm", "title": "Storyboard18 — FY26 loss + Pizza Hut openings collapse"},
            {"url": "https://www.storyboard18.com/brand-marketing/devyani-international-stops-pizza-hut-expansion-focuses-on-kfc-growth-ws-l-98530.htm", "title": "Storyboard18 — Pizza Hut expansion freeze"},
            {"url": "https://scanx.trade/stock-market-news/companies/devyani-international-completes-registered-office-relocation-from-delhi-to-haryana/37023176", "title": "Scanx — Office relocation"},
            {"url": "https://www.screener.in/company/DEVYANI/consolidated/", "title": "Screener — Devyani consolidated"},
        ],
    },

    "whirlpool": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹2,496.86 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "₹145.25 cr", "note": "Strong summer base"},
            {"label": "Q2 FY25", "revenue": "₹1,712.99 cr", "ebitda": "₹87 cr", "ebitda_pct": "5.1%", "pat": "₹53.53 cr"},
            {"label": "Q3 FY25", "revenue": "₹1,564.90 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "₹26.80 cr"},
            {"label": "Q4 FY25", "revenue": "₹2,004.67 cr", "ebitda": "₹183 cr", "ebitda_pct": "9.1%", "pat": "₹119.47 cr", "note": "Includes ₹7 cr insurance gain on fire loss"},
            {"label": "Q1 FY26", "revenue": "₹2,432.32 cr", "ebitda": "₹211 cr", "ebitda_pct": "8.7%", "pat": "₹146.08 cr", "note": "Weak summer + early monsoon"},
            {"label": "Q2 FY26", "revenue": "₹1,647.27 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "—", "note": "Off-season"},
            {"label": "Q3 FY26", "revenue": "₹1,624 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "₹41.33 cr", "note": "PAT −20.5% YoY, −71.6% QoQ"},
            {"label": "Q4 FY26", "revenue": "₹2,030 cr", "ebitda": "₹100 cr", "ebitda_pct": "4.9%", "pat": "₹80 cr", "note": "EBITDA −40.9% YoY; BEE + e-waste cost hit"},
        ],
        "signals": [
            {"date": "2024-02-22", "kind": "other", "headline": "Whirlpool Corp (USA) sold 24% stake via block deal", "detail": "~$468 mn; parent stake 75% → 51%; intent to reduce further to ~20%."},
            {"date": "2025-05-20", "kind": "concall", "headline": "Q4 FY25: PAT ₹119 cr (+50% YoY); FY25 PAT ₹359 cr (+65%)"},
            {"date": "2025-07-28", "kind": "concall", "headline": "Q1 FY26 concall flags 'very significant decline' in AC + refrigerator industry"},
            {"date": "2025-11-27", "kind": "other", "headline": "Whirlpool Mauritius sold 11.23% stake at ~14% discount for ₹1,489 cr"},
            {"date": "2026-01-01", "kind": "regulatory", "headline": "New BEE star-rating norms effective; ISEER recalibration", "detail": "5-7% AC and 3-5% refrigerator BOM step-up — permanent cost shift."},
            {"date": "2026-02-13", "kind": "concall", "headline": "Q3 FY26: PAT ₹41.3 cr (−20.5% YoY, −71.6% QoQ)"},
            {"date": "2026-05-20", "kind": "concall", "headline": "Q4 FY26: standalone EBITDA −40.9% YoY; FY26 PAT ₹293.75 cr (−18.2%)", "url": "https://www.business-standard.com/markets/capital-market-news/whirlpool-of-india-q4-pat-drops-33-yoy-to-rs-80-cr-126052100545_1.html"},
            {"date": "2026-05-21", "kind": "analyst", "headline": "Stock rebounds ~18% from 52w low post results"},
        ],
        "sources": [
            {"url": "https://www.business-standard.com/markets/capital-market-news/whirlpool-of-india-q4-pat-drops-33-yoy-to-rs-80-cr-126052100545_1.html", "title": "Business Standard — Q4 FY26"},
            {"url": "https://indianretailer.com/news/retail-india-news-whirlpool-india-q4-profit-drops-40-pc-fy26", "title": "Indian Retailer — Q4 FY26"},
            {"url": "https://www.whalesbook.com/corporate-news/English/consumer-products/Whirlpool-India-Posts-Revenue-Growth-But-Profits-Tumble-in-Q4-FY26/6a10268dbf3d6c9fcdc556e7", "title": "Whalesbook — Q4 FY26"},
            {"url": "https://www.investywise.com/whirlpool-of-india-q4-fy-2025-26-financial-results-overview/", "title": "Investywise — FY26 overview"},
            {"url": "https://www.marketsmojo.com/news/result-analysis/whirlpool-of-india-q4-fy26-profit-surge-masks-underlying-margin-pressures-4001893", "title": "MarketsMojo — Q4 FY26"},
            {"url": "https://www.screener.in/company/WHIRLPOOL/consolidated/", "title": "Screener — Whirlpool consolidated"},
            {"url": "https://upstox.com/news/business-news/stocks/whirlpool-corporation-sells-24percent-stake-in-india-unit/article-69956/", "title": "Upstox — Whirlpool Corp 24% stake sale"},
        ],
    },

    "ndtv": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹93.92 cr", "ebitda": "−₹46 cr", "ebitda_pct": "neg", "pat": "−₹46.75 cr", "note": "Political-ad tailwind; loss widens 5.7x on production costs"},
            {"label": "Q2 FY25", "revenue": "₹111.32 cr", "ebitda": "−₹43 cr", "ebitda_pct": "neg", "pat": "−₹52.77 cr"},
            {"label": "Q3 FY25", "revenue": "₹133 cr", "ebitda": "−₹42 cr", "ebitda_pct": "neg", "pat": "−₹55.48 cr"},
            {"label": "Q4 FY25", "revenue": "₹127.05 cr", "ebitda": "−₹49 cr", "ebitda_pct": "neg", "pat": "−₹61.97 cr", "note": "Production costs ~₹51 cr"},
            {"label": "Q1 FY26", "revenue": "₹108 cr", "ebitda": "−₹58 cr", "ebitda_pct": "neg", "pat": "−₹70 cr [unverified]"},
            {"label": "Q2 FY26", "revenue": "₹122 cr", "ebitda": "−₹57 cr", "ebitda_pct": "neg", "pat": "−₹74 cr [unverified]"},
            {"label": "Q3 FY26", "revenue": "₹150 cr", "ebitda": "−₹61 cr", "ebitda_pct": "neg", "pat": "−₹80.25 cr", "note": "Revenue +13% YoY; loss continues to deepen"},
            {"label": "Q4 FY26", "revenue": "₹147.96 cr", "ebitda": "−₹97.84 cr", "ebitda_pct": "neg", "pat": "−₹98.57 cr", "note": "10th straight loss qtr; production costs ₹84 cr (+64% YoY)"},
        ],
        "signals": [
            {"date": "2022-12-30", "kind": "other", "headline": "Adani Group completes control of NDTV via VCPL + open offer + Roy family block deal"},
            {"date": "2024-05-01", "kind": "launch", "headline": "NDTV Marathi launched — first non-Hindi regional channel"},
            {"date": "2024-10-21", "kind": "launch", "headline": "NDTV World global channel inaugurated by PM Modi at NDTV World Summit 2024"},
            {"date": "2025-01-25", "kind": "concall", "headline": "Q3 FY25: loss widens to ₹55.48 cr; mgmt flags 'investment phase'"},
            {"date": "2025-06-26", "kind": "regulatory", "headline": "BARC shifts to weekly unrolled viewership data; NDTV TRP visibility constrained"},
            {"date": "2026-04-25", "kind": "concall", "headline": "Q4 FY25: loss ₹61.97 cr; production costs flagged as primary headwind"},
            {"date": "2026-05-15", "kind": "concall", "headline": "FY26 annual: net loss ₹323.16 cr (vs ₹218.01 cr) — 48% deeper despite 13.6% revenue growth", "detail": "Expenses ₹855 cr vs ₹689 cr; marketing 44.7% of revenue", "url": "https://www.pitchonnet.com/pitch-feature/ndtvs-fy26-loss-widens-48-even-as-revenue-posts-double-digit-growth-39846.html"},
        ],
        "sources": [
            {"url": "https://indiantelevision.com/mam/ndtv-fy26-loss-widens-to-rs-323-crore-revenue-rises/", "title": "Indian Television — FY26 loss"},
            {"url": "https://www.pitchonnet.com/pitch-feature/ndtvs-fy26-loss-widens-48-even-as-revenue-posts-double-digit-growth-39846.html", "title": "Pitchonnet — FY26 loss widens 48%"},
            {"url": "https://www.exchange4media.com/media-tv-news/ndtv-fy26-loss-widens-48-despite-double-digit-revenue-growth-154296.html", "title": "Exchange4media — FY26 loss"},
            {"url": "https://bestmediainfo.com/mediainfo/television/ndtv-q4-revenue-grows-165-ebitda-loss-widens-to-rs-97-crore-11780955", "title": "Best Media Info — Q4 FY26"},
            {"url": "https://www.marketsmojo.com/news/result-analysis/ndtv-q4-fy26-losses-deepen-as-operational-challenges-intensify-3970203", "title": "MarketsMojo — Q4 FY26"},
            {"url": "https://www.screener.in/company/NDTV/consolidated/", "title": "Screener — NDTV consolidated"},
            {"url": "https://bestmediainfo.com/mediainfo/television/pm-modi-inaugurates-global-indian-news-channel-ndtv-world-7343858", "title": "Best Media Info — NDTV World launch"},
        ],
    },

    "indus-towers": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹7,383 cr", "ebitda": "₹4,545 cr", "ebitda_pct": "61.6%", "pat": "₹1,926 cr"},
            {"label": "Q2 FY25", "revenue": "₹7,465 cr", "ebitda": "₹4,550 cr [unverified]", "ebitda_pct": "61.0%", "pat": "₹2,224 cr", "note": "₹1,077 cr Vi doubtful-receivables write-back"},
            {"label": "Q3 FY25", "revenue": "₹7,547 cr", "ebitda": "₹7,000 cr [unverified]", "ebitda_pct": "—", "pat": "₹4,003 cr", "note": "₹3,024 cr Vi provision reversal — peak one-off"},
            {"label": "Q4 FY25", "revenue": "₹7,728 cr", "ebitda": "₹4,393 cr", "ebitda_pct": "56.9%", "pat": "₹1,779 cr", "note": "Dividend deferral disappoints; stock −7%"},
            {"label": "Q1 FY26", "revenue": "₹8,058 cr", "ebitda": "₹4,390 cr", "ebitda_pct": "54.5%", "pat": "₹1,737 cr", "note": "Margin compression"},
            {"label": "Q2 FY26", "revenue": "₹8,188 cr", "ebitda": "₹4,613 cr", "ebitda_pct": "56.3%", "pat": "₹1,839 cr"},
            {"label": "Q3 FY26", "revenue": "₹8,146 cr", "ebitda": "₹4,509 cr", "ebitda_pct": "55.3%", "pat": "₹1,776 cr", "note": "PAT −55.6% YoY on lapsed Vi write-back base"},
            {"label": "Q4 FY26", "revenue": "₹8,101 cr", "ebitda": "₹4,464 cr", "ebitda_pct": "55.1%", "pat": "₹1,793 cr", "note": "₹14/share dividend; sharing factor 1.62"},
        ],
        "signals": [
            {"date": "2024-10-22", "kind": "concall", "headline": "Q2 FY25: ₹1,077 cr Vi write-back lifts PAT +71.6% YoY"},
            {"date": "2025-01-23", "kind": "concall", "headline": "Q3 FY25: ₹3,024 cr Vi reversal drives PAT +160% YoY", "detail": "Peak one-off quarter; FY25 total Vi collection ₹2,328 cr"},
            {"date": "2025-05-02", "kind": "concall", "headline": "Q4 FY25 result + dividend deferral; stock −7% intraday"},
            {"date": "2025-11-04", "kind": "other", "headline": "Bharti Airtel board approves raising Indus stake by up to 5%"},
            {"date": "2026-02-05", "kind": "other", "headline": "Bharti Airtel executes open-market buys; stake 51.03% → 51.18%"},
            {"date": "2026-04-02", "kind": "analyst", "headline": "US 26% reciprocal tariff triggers FII outflow on INDUSTOWER"},
            {"date": "2026-05-04", "kind": "concall", "headline": "Q4 FY26 + FY26 results: FY26 PAT ₹7,145 cr (−28% YoY)", "detail": "Vi reversal tailwind exhausted (FY26 ₹2.7 bn vs FY25 ₹50.9 bn)", "url": "https://www.business-standard.com/markets/capital-market-news/indus-towers-reports-marginal-rise-in-q4-fy26-profit-126050400450_1.html"},
            {"date": "2026-04-30", "kind": "analyst", "headline": "Stock at ~₹325 vs 52w high ₹460 (−29%); FII holding ~11.4%"},
        ],
        "sources": [
            {"url": "https://www.industowers.com/investor/result/", "title": "Indus Towers IR — Quarterly Results"},
            {"url": "https://www.screener.in/company/INDUSTOWER/consolidated/", "title": "Screener — INDUSTOWER"},
            {"url": "https://www.business-standard.com/markets/capital-market-news/indus-towers-reports-marginal-rise-in-q4-fy26-profit-126050400450_1.html", "title": "Business Standard — Q4 FY26"},
            {"url": "https://www.business-standard.com/companies/results/indus-towers-q3fy25-results-net-profit-rises-160-to-rs-4-003-crore-125012301551_1.html", "title": "Business Standard — Q3 FY25 (+160%)"},
            {"url": "https://www.business-standard.com/markets/capital-market-news/indus-towers-declines-after-q1-pat-falls-nearly-10-yoy-macro-tower-counts-stands-at-2-51-lakh-125073100255_1.html", "title": "Business Standard — Q1 FY26"},
            {"url": "https://www.marketsmojo.com/news/result-analysis/indus-towers-q3-fy26-profit-declines-5564-yoy-despite-revenue-growth-3816886", "title": "MarketsMojo — Q3 FY26"},
            {"url": "https://univest.in/blogs/why-is-indus-towers-share-price-falling", "title": "Univest — Why share is falling"},
        ],
    },

    "rba-burger-king": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹646.69 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "−₹49.36 cr"},
            {"label": "Q2 FY25", "revenue": "₹632.43 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "−₹65.45 cr"},
            {"label": "Q3 FY25", "revenue": "₹647.83 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "−₹54.71 cr"},
            {"label": "Q4 FY25", "revenue": "₹632.55 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "−₹60.44 cr", "note": "FY25 consol loss ₹232.79 cr"},
            {"label": "Q1 FY26", "revenue": "₹552.30 cr", "ebitda": "₹22.5 cr [unverified]", "ebitda_pct": "4.1%", "pat": "−₹41.94 cr"},
            {"label": "Q2 FY26", "revenue": "₹568.65 cr", "ebitda": "₹11.3 cr", "ebitda_pct": "2.0%", "pat": "−₹63.33 cr"},
            {"label": "Q3 FY26", "revenue": "₹714.65 cr", "ebitda": "₹24.6 cr", "ebitda_pct": "7.0%", "pat": "−₹43.54 cr", "note": "Highest-ever quarterly revenue; India SSG +5.1%"},
            {"label": "Q4 FY26", "revenue": "₹706.84 cr", "ebitda": "₹99.2 cr [India std]", "ebitda_pct": "—", "pat": "−₹43.01 cr", "note": "India SSG +6.3% (best in 12Q); ₹120 cr Indonesia impairment booked"},
        ],
        "signals": [
            {"date": "2026-05-20", "kind": "other", "headline": "CCI approves QSR Asia / Lenexis Foodworks-led control change at ₹70.39/share", "detail": "Open offer ₹1,456 cr for 26% stake"},
            {"date": "2026-05-29", "kind": "concall", "headline": "FY26: ₹120 cr Indonesia (Popeyes) impairment booked", "url": "https://www.marketsmojo.com/news/result-analysis/restaurant-brands-asia-q4-fy26-losses-persist-despite-revenue-growth-as-expansion-costs-weigh-3993398"},
            {"date": "2026-05-29", "kind": "concall", "headline": "Popeyes Indonesia FY26 store EBITDA loss IDR 25 bn; BK Indonesia store-EBITDA positive IDR 8 bn"},
            {"date": "2026-03-31", "kind": "other", "headline": "India network crosses 581 stores; FY26 India revenue ₹2,272 cr (+15.4% YoY)"},
            {"date": "2026-05-29", "kind": "concall", "headline": "Q4 India SSG +6.3% — strongest in 12 quarters; consol loss narrows to ₹43 cr"},
            {"date": "2025-11-21", "kind": "regulatory", "headline": "Labour Codes implementation: ₹2.25 cr exceptional charge"},
            {"date": "2026-02-13", "kind": "other", "headline": "EGM approves preferential issue of 12.86 cr equity + 8.57 cr warrants at ₹70 to Lenexis-led consortium"},
            {"date": "2026-05-29", "kind": "other", "headline": "Promoter change: QSR Asia / F&B Asia Ventures exit; Lenexis Foodworks + Inspira Global become new promoters"},
        ],
        "sources": [
            {"url": "https://www.marketsmojo.com/news/result-analysis/restaurant-brands-asia-q4-fy26-losses-persist-despite-revenue-growth-as-expansion-costs-weigh-3993398", "title": "MarketsMojo — RBA Q4 FY26"},
            {"url": "https://scanx.trade/stock-market-news/companies/restaurant-brands-asia-reports-fy26-annual-results-standalone-loss-widens-to-1-591-40-million-on-exceptional-charges/40336466", "title": "Scanx — RBA FY26 results"},
            {"url": "https://www.whalesbook.com/corporate-news/English/consumer-products/Restaurant-Brands-Asia-FY26-Revenue-Jumps-But-Net-Loss-Widens-Sharply-to-indian-rupee235-Cr/6a05f082335e73ece27c5845", "title": "Whalesbook — RBA FY26"},
            {"url": "https://scanx.trade/stock-market-news/companies/cci-approves-acquisition-of-restaurant-brands-asia/40845052", "title": "Scanx — CCI approves acquisition"},
            {"url": "https://www.prysm.fi/news/restaurant-brands-asia-q3-fy26-results-net-loss-widens-to-7038-crore", "title": "Prysm — Q3 FY26"},
            {"url": "https://www.marketsmojo.com/news/result-analysis/restaurant-brands-asia-q2-fy26-losses-narrow-but-profitability-remains-elusive-3659144", "title": "MarketsMojo — Q2 FY26"},
        ],
    },

    "relaxo": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹748 cr", "ebitda": "₹99 cr", "ebitda_pct": "13.2%", "pat": "₹44 cr", "note": "Election + heatwave drag; PAT −21% YoY"},
            {"label": "Q2 FY25", "revenue": "₹679 cr", "ebitda": "₹88 cr", "ebitda_pct": "13.0%", "pat": "₹37 cr"},
            {"label": "Q3 FY25", "revenue": "₹667 cr", "ebitda": "₹83 cr", "ebitda_pct": "12.4%", "pat": "₹33 cr"},
            {"label": "Q4 FY25", "revenue": "₹695 cr", "ebitda": "₹112 cr", "ebitda_pct": "16.1%", "pat": "₹56 cr"},
            {"label": "Q1 FY26", "revenue": "₹655 cr", "ebitda": "₹99 cr", "ebitda_pct": "15.2%", "pat": "₹49 cr", "note": "Revenue −12.6% YoY"},
            {"label": "Q2 FY26", "revenue": "₹629 cr", "ebitda": "₹81 cr", "ebitda_pct": "12.9%", "pat": "₹36 cr", "note": "Volumes −4.7% YoY"},
            {"label": "Q3 FY26", "revenue": "₹667 cr", "ebitda": "₹69 cr", "ebitda_pct": "10.4%", "pat": "₹26 cr", "note": "PAT −19.6% YoY; GST 2.0 destocking"},
            {"label": "Q4 FY26", "revenue": "₹751 cr", "ebitda": "₹124 cr", "ebitda_pct": "16.5%", "pat": "₹68 cr", "note": "Recovery; PAT +20.4% YoY"},
        ],
        "signals": [
            {"date": "2025-11-09", "kind": "concall", "headline": "Q2 FY26: volumes −4.7% YoY, mid-market demand weakness"},
            {"date": "2026-01-17", "kind": "regulatory", "headline": "GST 2.0 rate cut to 5% on sub-₹2,500 footwear", "detail": "Distributor destocking; Q3 EBITDA margin collapses to 10.4%"},
            {"date": "2026-03-11", "kind": "cfo", "headline": "CFO Prince Jain resigns with IMMEDIATE EFFECT", "url": "https://scanx.trade/stock-market-news/stocks/relaxo-footwears-cfo-prince-jain-steps-down-from-position/34778571"},
            {"date": "2026-03-26", "kind": "cfo", "headline": "Board appoints Amit Roy (ex-Jubilant CA+CMA) as new CFO"},
            {"date": "2026-04-01", "kind": "cfo", "headline": "Amit Roy assumes CFO role"},
            {"date": "2026-05-29", "kind": "concall", "headline": "Q4 FY26: revenue +8.1% YoY to ₹751 cr; PAT +20.4%; stock rallies 13%"},
            {"date": "2026-05-29", "kind": "concall", "headline": "FY26 revenue ₹2,702 cr (−3.1% YoY) — first revenue decline in years"},
            {"date": "2026-05-30", "kind": "concall", "headline": "FY27 guidance: 4–5% volume growth, ~100bps margin expansion"},
        ],
        "sources": [
            {"url": "https://www.equitybulls.com/category.php?id=371406", "title": "EquityBulls — Q4 FY26 results"},
            {"url": "https://www.marketsmojo.com/news/result-analysis/relaxo-footwears-q4-fy26-strong-quarter-masks-deeper-structural-concerns-4022097", "title": "MarketsMojo — Q4 FY26"},
            {"url": "https://tradebrains.in/relaxo-footwears-stock-rallies-13-as-q4-profit-jumps-20-on-core-volume-recovery/", "title": "Tradebrains — Q4 rally"},
            {"url": "https://scanx.trade/stock-market-news/companies/relaxo-footwears-appoints-amit-roy-as-chief-financial-officer-effective-april-1-2026/36093391", "title": "Scanx — Amit Roy CFO"},
            {"url": "https://scanx.trade/stock-market-news/stocks/relaxo-footwears-cfo-prince-jain-steps-down-from-position/34778571", "title": "Scanx — CFO Prince Jain steps down"},
            {"url": "https://www.marketsmojo.com/news/result-analysis/relaxo-footwears-q2-fy26-margin-pressures-mount-as-revenue-decline-continues-3712170", "title": "MarketsMojo — Q2 FY26"},
            {"url": "https://relaxofootwear.com/pages/financial-results", "title": "Relaxo IR — Financial results"},
        ],
    },

    "smc-global": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹448 cr", "ebitda": "₹125 cr", "ebitda_pct": "28%", "pat": "₹53 cr", "note": "Pre-SEBI reform peak; PAT +77% YoY"},
            {"label": "Q2 FY25", "revenue": "₹451 cr", "ebitda": "₹119 cr", "ebitda_pct": "26%", "pat": "₹46 cr"},
            {"label": "Q3 FY25", "revenue": "₹455 cr", "ebitda": "₹112 cr", "ebitda_pct": "25%", "pat": "₹44 cr", "note": "First full quarter post SEBI F&O reform"},
            {"label": "Q4 FY25", "revenue": "₹421 cr", "ebitda": "₹63 cr", "ebitda_pct": "15%", "pat": "₹4 cr", "note": "Margin collapse"},
            {"label": "Q1 FY26", "revenue": "₹425 cr", "ebitda": "₹100 cr", "ebitda_pct": "24%", "pat": "₹30 cr", "note": "PAT −44% YoY"},
            {"label": "Q2 FY26", "revenue": "₹440 cr", "ebitda": "₹84 cr", "ebitda_pct": "19%", "pat": "₹21 cr", "note": "PBT −54% YoY"},
            {"label": "Q3 FY26", "revenue": "₹495 cr", "ebitda": "₹102 cr", "ebitda_pct": "21%", "pat": "₹31 cr"},
            {"label": "Q4 FY26", "revenue": "₹517 cr", "ebitda": "₹90 cr", "ebitda_pct": "17%", "pat": "₹22 cr", "note": "PAT +424% on weak Q4 FY25 base"},
        ],
        "signals": [
            {"date": "2024-10-01", "kind": "regulatory", "headline": "SEBI announces 6-measure F&O framework", "url": "https://www.business-standard.com/markets/news/sebi-announces-six-key-changes-to-curb-speculation-in-derivatives-trading-124100101316_1.html"},
            {"date": "2024-11-21", "kind": "regulatory", "headline": "SEBI F&O reform LIVE: index contract size 3x; Nifty lot 25→75", "url": "https://www.business-standard.com/markets/news/new-f-o-rule-to-come-into-effect-from-thursday-nov-21-here-s-what-changes-124112000292_1.html"},
            {"date": "2025-03-31", "kind": "concall", "headline": "Q4 FY25: OPM 15%, PAT crashes to ₹4 cr consolidated"},
            {"date": "2025-07-29", "kind": "concall", "headline": "Q1 FY26: PAT −43.6% YoY to ₹30 cr; guides 10-12% revenue growth"},
            {"date": "2026-04-02", "kind": "pledge", "headline": "Annual SEBI takeover disclosure: Pulin Investments 58% of holding encumbered"},
            {"date": "2026-05-04", "kind": "concall", "headline": "Q4 + FY26: revenue ₹1,877 cr (+5.7%); PAT ₹103 cr (−29.7%); ₹0.60/share dividend"},
            {"date": "2026-05-04", "kind": "concall", "headline": "Q4 EBITDA ₹89.7 cr (+42% YoY); insurance broking 34% of mix"},
            {"date": "2026-06-15", "kind": "other", "headline": "Record date for ₹0.60 dividend; AGM Jun 26 to approve ₹3,000 cr borrowing limit"},
        ],
        "sources": [
            {"url": "https://www.screener.in/company/SMCGLOBAL/consolidated/", "title": "Screener — SMC Global"},
            {"url": "https://www.marketsmojo.com/news/result-analysis/smc-global-securities-q4-fy26-profit-surge-masks-persistent-margin-pressures-3973051", "title": "MarketsMojo — Q4 FY26"},
            {"url": "https://www.marketsmojo.com/news/result-analysis/smc-global-securities-q2-fy26-profit-plunges-54-as-margins-compress-amid-competitive-pressures-3661179", "title": "MarketsMojo — Q2 FY26"},
            {"url": "https://tradebrains.in/smc-global-shares-fall-1-5-as-fy26-profit-falls-30-despite-sharp-q4-recovery/", "title": "Tradebrains — FY26 -30%"},
            {"url": "https://www.whalesbook.com/corporate-news/English/bankingfinance/SMC-Global-Securities-PAT-Declines-29percent-to-indian-rupee103-Crore-for-FY26/6a215f16f554d3868a8e6f76", "title": "Whalesbook — FY26 PAT"},
            {"url": "https://www.business-standard.com/markets/news/new-f-o-rule-to-come-into-effect-from-thursday-nov-21-here-s-what-changes-124112000292_1.html", "title": "Business Standard — F&O rule effect"},
        ],
    },

    "jubilant-foodworks": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹1,545.8 cr", "ebitda": "₹303.8 cr", "ebitda_pct": "19.7%", "pat": "₹60.9 cr"},
            {"label": "Q2 FY25", "revenue": "₹1,955.0 cr", "ebitda": "₹388.6 cr", "ebitda_pct": "19.9%", "pat": "₹71.5 cr", "note": "DP Eurasia consolidation begins"},
            {"label": "Q3 FY25", "revenue": "₹2,103.0 cr", "ebitda": "₹406.3 cr", "ebitda_pct": "19.3%", "pat": "₹62.3 cr"},
            {"label": "Q4 FY25", "revenue": "₹2,095.0 cr", "ebitda": "₹391.9 cr", "ebitda_pct": "18.7%", "pat": "₹55.9 cr", "note": "Domino's India LFL 12.1% (high base)"},
            {"label": "Q1 FY26", "revenue": "₹2,261.1 cr", "ebitda": "₹438.6 cr", "ebitda_pct": "19.4%", "pat": "₹97.2 cr"},
            {"label": "Q2 FY26", "revenue": "₹2,343.6 cr", "ebitda": "₹479.8 cr", "ebitda_pct": "20.5%", "pat": "₹109.9 cr", "note": "Domino's India LFL +9.1%"},
            {"label": "Q3 FY26", "revenue": "₹2,437.2 cr", "ebitda": "₹482.4 cr", "ebitda_pct": "19.8%", "pat": "₹98.1 cr"},
            {"label": "Q4 FY26", "revenue": "₹2,499.5 cr", "ebitda": "₹484.9 cr", "ebitda_pct": "19.4%", "pat": "₹93.5 cr", "note": "Domino's India SSG only +0.2%; stock −8% intraday"},
        ],
        "signals": [
            {"date": "2026-05-20", "kind": "concall", "headline": "Q4 FY26: Domino's India SSG just +0.2%; stock −8% despite PAT +67%", "url": "https://www.storyboard18.com/brand-marketing/jubilant-foodworks-q4-profit-jumps-67-percent-on-dominos-value-strategy-ws-l-98724.htm"},
            {"date": "2026-05-21", "kind": "concall", "headline": "Mgmt flags near-term margin headwinds; Ramadan + exam season + Navratri calendar"},
            {"date": "2026-02-05", "kind": "concall", "headline": "Q3 FY26: revenue ₹2,437 cr (+13.3%); PAT +93.9% YoY; EBITDA 19.8%"},
            {"date": "2025-11-13", "kind": "concall", "headline": "Q2 FY26: Domino's India LFL +9.1%, Turkey LFL +5.6%, Sri Lanka +81%"},
            {"date": "2024-12-30", "kind": "other", "headline": "Completes squeeze-out / delisting of DP Eurasia (Turkey Domino's)"},
            {"date": "2026-05-20", "kind": "other", "headline": "Store network 3,636 outlets (net +69 in Q4); Popeyes +28% SSG"},
            {"date": "2022-09-05", "kind": "cfo", "headline": "Sameer Khetarpal (ex-Amazon India) takes over as CEO & MD"},
            {"date": "2022-01-20", "kind": "launch", "headline": "First Popeyes outlet opened in Koramangala, Bangalore"},
        ],
        "sources": [
            {"url": "https://www.storyboard18.com/brand-marketing/jubilant-foodworks-q4-profit-jumps-67-percent-on-dominos-value-strategy-ws-l-98724.htm", "title": "Storyboard18 — Q4 FY26"},
            {"url": "https://www.business-standard.com/markets/capital-market-news/jubilant-foodworks-slips-after-management-flags-near-term-margin-headwinds-126052100642_1.html", "title": "Business Standard — Margin headwinds"},
            {"url": "https://www.marketsmojo.com/news/result-analysis/jubilant-foodworks-q4-fy26-strong-finish-masks-margin-pressures-and-valuation-concerns-4001882", "title": "MarketsMojo — Q4 FY26"},
            {"url": "https://www.whalesbook.com/news/English/consumer-products/Jubilant-FoodWorks-Q3FY26-Profit-Surges-94percent-Revenue-Up-133percent/699c76f1ee97f501b0ebe4e1", "title": "Whalesbook — Q3 FY26"},
            {"url": "https://www.screener.in/company/JUBLFOOD/consolidated/", "title": "Screener — Jubilant FoodWorks"},
            {"url": "https://www.jubilantfoodworks.com/Uploads/Files/1264foodfile-Q2FY26_EarningsPresentation.pdf", "title": "Q2 FY26 Earnings Presentation"},
        ],
    },

    "dr-lal": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹602 cr", "ebitda": "₹172 cr", "ebitda_pct": "28.6%", "pat": "₹108 cr"},
            {"label": "Q2 FY25", "revenue": "₹660 cr", "ebitda": "₹202 cr", "ebitda_pct": "30.7%", "pat": "₹129 cr", "note": "Peak seasonal margin"},
            {"label": "Q3 FY25", "revenue": "₹597 cr", "ebitda": "₹154 cr", "ebitda_pct": "25.8%", "pat": "₹98 cr"},
            {"label": "Q4 FY25", "revenue": "₹603 cr", "ebitda": "₹169 cr", "ebitda_pct": "28.1%", "pat": "₹156 cr", "note": "₹41 cr one-off tax benefit from Suburban Diagnostics liquidation"},
            {"label": "Q1 FY26", "revenue": "₹670 cr", "ebitda": "₹192 cr", "ebitda_pct": "28.7%", "pat": "₹134 cr"},
            {"label": "Q2 FY26", "revenue": "₹731 cr", "ebitda": "₹224 cr", "ebitda_pct": "30.6%", "pat": "₹152 cr"},
            {"label": "Q3 FY26", "revenue": "₹660 cr", "ebitda": "₹179 cr", "ebitda_pct": "27.1%", "pat": "₹91 cr", "note": "₹30.1 cr Labour Code one-off"},
            {"label": "Q4 FY26", "revenue": "₹703 cr", "ebitda": "₹187 cr", "ebitda_pct": "26.6%", "pat": "₹132 cr", "note": "PAT −15.1% YoY (vs Q4 FY25 tax one-off)"},
        ],
        "signals": [
            {"date": "2025-02-18", "kind": "other", "headline": "Board approves voluntary liquidation of Suburban Diagnostics subsidiary"},
            {"date": "2025-04-30", "kind": "concall", "headline": "Q4 FY25: ₹41 cr one-time deferred tax benefit booked"},
            {"date": "2026-01-23", "kind": "concall", "headline": "Q3 FY26: ₹30.1 cr exceptional Labour Codes provision"},
            {"date": "2026-02-27", "kind": "regulatory", "headline": "NCLT Mumbai grants final approval for Suburban Diagnostics liquidation"},
            {"date": "2026-04-30", "kind": "other", "headline": "Board approves Maharashtra acquisition (Shahbazkers Diagnostic) for up to ₹20 cr; Dubai subsidiary approved"},
            {"date": "2026-05-04", "kind": "analyst", "headline": "Goldman Sell ₹1,300 vs Nomura Buy ₹1,860 — polarized on Tata 1mg pricing pressure", "url": "https://scanx.trade/stock-market-news/investment-ideas/divergent-analyst-views-on-dr-lal-pathlabs-nomura-bullish-at-1-860-goldman-sachs-cautious-at-1-300/39411949"},
            {"date": "2026-05-04", "kind": "concall", "headline": "FY27 guidance: 13–15% revenue growth, 27–28% EBITDA margin reaffirmed"},
        ],
        "sources": [
            {"url": "https://www.business-standard.com/companies/quarterly-results/dr-lal-pathlabs-q4fy26-results-net-profit-falls-15-revenue-rises-16-6-126043001444_1.html", "title": "Business Standard — Q4 FY26"},
            {"url": "https://www.equitybulls.com/category.php?id=369852", "title": "EquityBulls — Q4 FY26"},
            {"url": "https://www.whalesbook.com/corporate-news/English/healthcarebiotech/Dr-Lal-PathLabs-FY26-Revenue-Hits-indian-rupee2763-Cr-Buys-Maharashtra-Lab/69f331d908235f0c2a1f5d55", "title": "Whalesbook — FY26"},
            {"url": "https://scanx.trade/stock-market-news/investment-ideas/divergent-analyst-views-on-dr-lal-pathlabs-nomura-bullish-at-1-860-goldman-sachs-cautious-at-1-300/39411949", "title": "Scanx — Goldman vs Nomura"},
            {"url": "https://scanx.trade/stock-market-news/corporate-actions/dr-lal-pathlabs-receives-nclt-approval-for-voluntary-liquidation-of-suburban-diagnostics-subsidiary/34683267", "title": "Scanx — NCLT Suburban liquidation"},
            {"url": "https://www.screener.in/company/LALPATHLAB/consolidated/", "title": "Screener — Dr Lal PathLabs"},
        ],
    },

    "capital-india-finance": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹158 cr", "ebitda": "−₹0.3 cr", "ebitda_pct": "neg", "pat": "−₹6.4 cr"},
            {"label": "Q2 FY25", "revenue": "₹143 cr", "ebitda": "₹5.3 cr", "ebitda_pct": "4%", "pat": "₹0.6 cr"},
            {"label": "Q3 FY25", "revenue": "₹135 cr", "ebitda": "₹6.0 cr", "ebitda_pct": "4%", "pat": "−₹1.9 cr"},
            {"label": "Q4 FY25", "revenue": "₹139 cr", "ebitda": "₹3.0 cr", "ebitda_pct": "2%", "pat": "−₹2.6 cr"},
            {"label": "Q1 FY26", "revenue": "₹123 cr", "ebitda": "₹2.0 cr", "ebitda_pct": "2%", "pat": "−₹5.6 cr"},
            {"label": "Q2 FY26", "revenue": "₹132 cr", "ebitda": "−₹46.7 cr", "ebitda_pct": "neg", "pat": "₹44.7 cr", "note": "₹267 cr CIHL divestment one-time gain"},
            {"label": "Q3 FY26", "revenue": "₹147 cr", "ebitda": "₹0.6 cr", "ebitda_pct": "neg", "pat": "−₹5.2 cr"},
            {"label": "Q4 FY26", "revenue": "₹125 cr", "ebitda": "₹1.2 cr", "ebitda_pct": "1%", "pat": "−₹0.16 cr", "note": "Consolidated; standalone PAT −₹2.98 cr"},
        ],
        "signals": [
            {"date": "2025-08-15", "kind": "other", "headline": "Weaver Services completes ₹267 cr acquisition of Capital India Home Loans (CIHL)"},
            {"date": "2025-08-20", "kind": "regulatory", "headline": "RBI approves CIHL change-in-control to Weaver Services"},
            {"date": "2026-05-21", "kind": "concall", "headline": "Q4 FY26: consolidated net loss ₹0.16 cr; 5th consecutive consolidated loss quarter despite +243% FY26 PAT headline"},
            {"date": "2026-05-21", "kind": "concall", "headline": "FY26 AUM ₹1,227 cr (+22%); disbursements ₹753 cr (+62%); branches 29 → 46"},
            {"date": "2026-05-21", "kind": "concall", "headline": "Net NPA 1.32%; CAR 40.99% — well above regulatory floor"},
            {"date": "2026-05-21", "kind": "other", "headline": "FY26 debt raise of ₹600 cr including listed NCDs"},
            {"date": "2026-05-21", "kind": "concall", "headline": "FY27 strategic pivot announced: 'scalable MSME lending franchise'"},
        ],
        "sources": [
            {"url": "https://www.outlookbusiness.com/spotlight/news-wire/capital-india-finance-aum-grows-22-to-rs-1-227-crore-in-fy26-pat-rises-243", "title": "Outlook Business — AUM +22%, PAT +243%"},
            {"url": "https://scanx.trade/stock-market-news/companies/capital-india-finance-fy26-net-profit-rises-to-4-035-84-lakh/40831226", "title": "Scanx — FY26 PAT"},
            {"url": "https://www.marketsmojo.com/news/result-analysis/capital-india-finance-q4-fy26-mounting-losses-deepen-as-asset-quality-concerns-persist-4003154", "title": "MarketsMojo — Q4 FY26"},
            {"url": "https://smestreet.in/msme-opportunities/capital-india-finance-reports-fy26-results-fy27-focus-on-scalable-msme-lending-franchise-11861636", "title": "SMEStreet — MSME focus"},
            {"url": "https://www.screener.in/company/CIFL/consolidated/", "title": "Screener — CIFL"},
            {"url": "https://mnacritique.mergersindia.com/news/weaver-services-acquires-capital-india-home-loans-for-%E2%82%B9267-crore/", "title": "M&A Critique — Weaver acquires CIHL"},
        ],
    },

    "maruti": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹35,531 cr", "ebitda": "₹4,448 cr", "ebitda_pct": "12.5%", "pat": "₹3,650 cr", "note": "PAT +47% YoY"},
            {"label": "Q2 FY25", "revenue": "₹37,203 cr", "ebitda": "₹4,417 cr", "ebitda_pct": "11.9%", "pat": "₹3,069 cr", "note": "Margin −100 bps on higher discounts"},
            {"label": "Q3 FY25", "revenue": "₹38,764 cr", "ebitda": "₹4,663 cr", "ebitda_pct": "12.0%", "pat": "₹3,727 cr", "note": "Volume-led recovery"},
            {"label": "Q4 FY25", "revenue": "₹40,920 cr", "ebitda": "₹4,844 cr", "ebitda_pct": "12.0%", "pat": "₹3,911 cr", "note": "PAT margin ~10.07%"},
            {"label": "Q1 FY26", "revenue": "₹38,605 cr", "ebitda": "₹4,015 cr", "ebitda_pct": "10.4%", "pat": "₹3,792 cr", "note": "Margin compression begins"},
            {"label": "Q2 FY26", "revenue": "₹42,344 cr", "ebitda": "₹4,446 cr", "ebitda_pct": "10.5%", "pat": "₹3,293 cr"},
            {"label": "Q3 FY26", "revenue": "₹49,904 cr", "ebitda": "₹5,938 cr", "ebitda_pct": "11.9%", "pat": "₹3,879 cr", "note": "Revenue +20.6% YoY"},
            {"label": "Q4 FY26", "revenue": "₹52,463 cr", "ebitda": "₹6,157 cr", "ebitda_pct": "11.7%", "pat": "₹3,659 cr", "note": "PAT −6.4% YoY; missed ₹4,150 cr estimate"},
        ],
        "signals": [
            {"date": "2026-04-28", "kind": "concall", "headline": "Q4 FY26: PAT ₹3,659 cr (−6.4% YoY) misses ₹4,150 cr estimate", "url": "https://www.zeebiz.com/companies/news-maruti-q4fy26-results-highlights-profit-sales-margin-production-dividend-per-share-394454"},
            {"date": "2026-05-21", "kind": "other", "headline": "Price hike up to ₹30,000 effective June 2026 — second hike of CY26", "detail": "Cites 'sustained input cost inflation' and West Asia supply-chain disruption.", "url": "https://www.business-standard.com/amp/companies/news/maruti-suzuki-india-to-increase-prices-by-up-to-30-000-from-june-2026-126052101868_1.html"},
            {"date": "2026-05-01", "kind": "other", "headline": "Dealer discounts up to ₹70,000 in May 2026 on Victoris/Invicto/Brezza/Swift/Celerio/Alto", "url": "https://www.autocarindia.com/car-news/maruti-victoris-brezza-and-swift-get-discounts-of-up-to-rs-70000-in-may-2026-439654"},
            {"date": "2026-01-29", "kind": "concall", "headline": "Q3 FY26: revenue ₹49,904 cr (+20.6%); operating margin drops 240bps over 5 quarters"},
            {"date": "2025-10-29", "kind": "concall", "headline": "Q2 FY26: PAT +7% YoY to ₹3,293 cr; EBITDA margin 10.5% multi-quarter low"},
            {"date": "2026-04-28", "kind": "concall", "headline": "FY26 full-year: revenue ₹1,74,369 cr (+20.2%); PAT ₹14,445 cr (+1%); gross margin −312 bps to 13.12%"},
            {"date": "2026-06-01", "kind": "launch", "headline": "Brezza facelift confirmed for mid-2026 with 1.0L Boosterjet turbo + underbody CNG + L2 ADAS"},
            {"date": "2026-04-28", "kind": "concall", "headline": "Royalty drag to Suzuki Motor Corp continues — ~₹4,500 cr FY23 base"},
        ],
        "sources": [
            {"url": "https://www.zeebiz.com/companies/news-maruti-q4fy26-results-highlights-profit-sales-margin-production-dividend-per-share-394454", "title": "Zee Business — Q4 FY26"},
            {"url": "https://www.marketsmojo.com/news/result-analysis/maruti-suzuki-q4-fy26-revenue-surge-masks-profit-decline-in-volume-driven-quarter-3967173", "title": "MarketsMojo — Q4 FY26"},
            {"url": "https://www.investywise.com/maruti-suzuki-india-limited-q4-and-fy26-financial-results/", "title": "Investywise — FY26"},
            {"url": "https://www.screener.in/company/MARUTI/consolidated/", "title": "Screener — Maruti consolidated"},
            {"url": "https://www.business-standard.com/amp/companies/news/maruti-suzuki-india-to-increase-prices-by-up-to-30-000-from-june-2026-126052101868_1.html", "title": "Business Standard — ₹30,000 price hike"},
            {"url": "https://www.autocarindia.com/car-news/maruti-victoris-brezza-and-swift-get-discounts-of-up-to-rs-70000-in-may-2026-439654", "title": "Autocar India — May 2026 dealer discounts"},
            {"url": "https://www.marutisuzuki.com/corporate/media/press-releases/2026/april/maruti-suzuki-announces-financial-results-for-fy2025-26", "title": "Maruti IR — FY26 results"},
        ],
    },

    "vodafone-idea": {
        "quarterly": [
            {"label": "Q1 FY25", "revenue": "₹10,508 cr", "ebitda": "₹4,205 cr", "ebitda_pct": "40%", "pat": "−₹6,432 cr"},
            {"label": "Q2 FY25", "revenue": "₹10,932 cr", "ebitda": "₹4,550 cr", "ebitda_pct": "41.6%", "pat": "−₹7,176 cr"},
            {"label": "Q3 FY25", "revenue": "₹11,117 cr", "ebitda": "₹4,712 cr", "ebitda_pct": "42.4%", "pat": "−₹6,609 cr"},
            {"label": "Q4 FY25", "revenue": "₹11,015 cr", "ebitda": "₹4,660 cr", "ebitda_pct": "42.3%", "pat": "−₹7,167 cr"},
            {"label": "Q1 FY26", "revenue": "₹11,023 cr", "ebitda": "₹4,612 cr", "ebitda_pct": "41.8%", "pat": "−₹6,608 cr", "note": "ARPU ₹177"},
            {"label": "Q2 FY26", "revenue": "₹11,190 cr", "ebitda": "—", "ebitda_pct": "—", "pat": "−₹5,524 cr", "note": "ARPU ₹180"},
            {"label": "Q3 FY26", "revenue": "₹11,323 cr", "ebitda": "₹4,816 cr", "ebitda_pct": "42.5%", "pat": "−₹5,286 cr", "note": "ARPU ₹186"},
            {"label": "Q4 FY26", "revenue": "₹11,332 cr", "ebitda": "₹4,889 cr", "ebitda_pct": "43.1%", "pat": "+₹51,970 cr reported / −₹5,515 cr underlying", "note": "₹57,491 cr AGR exceptional gain; ARPU ₹190; subs 192.8 mn"},
        ],
        "signals": [
            {"date": "2024-09-19", "kind": "litigation", "headline": "Supreme Court dismisses Vi's curative petition on AGR dues judgment"},
            {"date": "2025-03-29", "kind": "regulatory", "headline": "Government converts ₹36,950 cr spectrum dues into equity at ₹10/share", "detail": "GoI stake to 48.99% — now largest shareholder."},
            {"date": "2025-04-21", "kind": "launch", "headline": "Vi commercially launches 5G across Mumbai, Delhi, Bengaluru, Chandigarh, Patna"},
            {"date": "2025-07-01", "kind": "other", "headline": "Industry-wide tariff hike ~10-21% across prepaid plans"},
            {"date": "2025-11-10", "kind": "concall", "headline": "Q2 FY26: loss ₹5,524 cr; ARPU ₹180"},
            {"date": "2026-02-15", "kind": "other", "headline": "Monthly subscriber additions turn positive — first time in years"},
            {"date": "2026-04-30", "kind": "regulatory", "headline": "DoT trims AGR dues to ₹64,046 cr (−₹23,649 cr); payments staggered to FY41", "url": "https://www.businesstoday.in/latest/corporate/story/rs23649-crore-relief-dot-trims-vodafone-ideas-agr-dues-allows-staggered-payment-till-fy41-528338-2026-04-30"},
            {"date": "2026-05-18", "kind": "concall", "headline": "Q4 FY26: reported PAT ₹51,970 cr (one-off); underlying loss ₹5,515 cr; 5G in 133 cities", "url": "https://www.business-standard.com/markets/capital-market-news/vodafone-idea-posts-pat-of-rs-51-970-crore-in-q4-fy26-126051800459_1.html"},
        ],
        "sources": [
            {"url": "https://www.business-standard.com/markets/capital-market-news/vodafone-idea-posts-pat-of-rs-51-970-crore-in-q4-fy26-126051800459_1.html", "title": "Business Standard — Q4 FY26 PAT"},
            {"url": "https://www.sahi.com/blogs/vodafone-idea-q4-fy26-results", "title": "Sahi.com — Q4 FY26"},
            {"url": "https://www.cmaknowledge.in/2026/05/vodafone-ideas-q4-fy26-financial-turnaround-agr-case-study.html", "title": "CMA Knowledge — AGR turnaround"},
            {"url": "https://www.businesstoday.in/latest/corporate/story/rs23649-crore-relief-dot-trims-vodafone-ideas-agr-dues-allows-staggered-payment-till-fy41-528338-2026-04-30", "title": "Business Today — DoT AGR relief"},
            {"url": "https://www.business-standard.com/companies/quarterly-results/vodafone-idea-q3-fy26-results-loss-arpu-revenue-earnings-share-price-agr-126012701273_1.html", "title": "Business Standard — Q3 FY26"},
            {"url": "https://univest.in/blogs/vodafone-idea-q4-results-2026", "title": "Univest — Q4 FY26"},
            {"url": "https://www.screener.in/company/IDEA/consolidated/", "title": "Screener — Vodafone Idea"},
        ],
    },
}
