#!/usr/bin/env python3
"""Phase 2 Step B — migrate foothold.db (SQLite) → Supabase Postgres.

Design:
- DDL is GENERATED from the live SQLite schema (pragma introspection), not
  hand-written — tables, PKs (identity where AUTOINCREMENT), FKs, UNIQUE
  constraints and secondary indexes are all derived. No guessing.
- Lift-and-shift typing: TEXT stays TEXT (ISO timestamps remain strings so
  app behaviour cannot drift), INTEGER→BIGINT, REAL→DOUBLE PRECISION.
- Dry run BY DEFAULT: builds everything inside a transaction on Postgres,
  verifies, then ROLLS BACK — proving the DDL and data load against the real
  server without leaving anything behind. --apply commits.
- Verification: full row-by-row comparison (ordered by PK) for every table,
  with float tolerance. Refuses to apply if target tables already exist
  (use --recreate to drop first).

Run:  cd pmis_v2 && python3 targets/migrate_to_pg.py [--apply] [--recreate]
"""

import os
import sys
import sqlite3
import math
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
import _env_bootstrap  # noqa: F401, E402 — loads DATABASE_URL / FOOTHOLD_DB_PATH

import psycopg  # noqa: E402

SQLITE_PATH = Path(os.environ.get("FOOTHOLD_DB_PATH", "").strip()
                   or HERE.parent / "data" / "foothold.db")

TABLES = [  # FK-safe order (parents first)
    "target_projects",
    "target_companies",
    "target_feedback",
    "target_communications",
    "target_followups",
    "target_quarterly",
    "target_signals",
    "target_sources",
    "target_research_logs",
    "target_capture_examples",
    "target_verticals",
    "target_headcount",
    "target_benchmarks",
]

TYPE_MAP = {"INTEGER": "BIGINT", "TEXT": "TEXT", "REAL": "DOUBLE PRECISION"}


def sqlite_conn():
    c = sqlite3.connect(f"file:{SQLITE_PATH}?mode=ro", uri=True)
    c.row_factory = sqlite3.Row
    return c


def table_ddl(sq, table: str) -> str:
    cols = sq.execute(f"PRAGMA table_info({table})").fetchall()
    fks = sq.execute(f"PRAGMA foreign_key_list({table})").fetchall()
    create_sql = sq.execute(
        "SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (table,)
    ).fetchone()["sql"]
    autoinc = "AUTOINCREMENT" in (create_sql or "").upper()

    lines = []
    for col in cols:
        name, ctype, notnull, dflt, pk = (col["name"], (col["type"] or "TEXT").upper(),
                                          col["notnull"], col["dflt_value"], col["pk"])
        pgtype = TYPE_MAP.get(ctype, "TEXT")
        if pk and ctype == "INTEGER" and autoinc:
            lines.append(f'  "{name}" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
            continue
        parts = [f'  "{name}" {pgtype}']
        if pk:
            parts.append("PRIMARY KEY")
        if notnull and not pk:
            parts.append("NOT NULL")
        if dflt is not None:
            parts.append(f"DEFAULT {dflt}")
        lines.append(" ".join(parts))

    # UNIQUE constraints (sqlite auto-indexes, origin 'u')
    for idx in sq.execute(f"PRAGMA index_list({table})").fetchall():
        if idx["origin"] == "u":
            icols = [r["name"] for r in sq.execute(f'PRAGMA index_info("{idx["name"]}")').fetchall()]
            quoted = ", ".join(f'"{c}"' for c in icols)
            lines.append(f"  UNIQUE ({quoted})")

    for fk in fks:
        lines.append(
            f'  FOREIGN KEY ("{fk["from"]}") REFERENCES "{fk["table"]}" ("{fk["to"]}")'
        )

    return f'CREATE TABLE "{table}" (\n' + ",\n".join(lines) + "\n)"


def index_ddls(sq, table: str):
    """Named secondary indexes (origin 'c'), translated verbatim-ish."""
    out = []
    for idx in sq.execute(f"PRAGMA index_list({table})").fetchall():
        if idx["origin"] != "c":
            continue
        icols = [r["name"] for r in sq.execute(f'PRAGMA index_info("{idx["name"]}")').fetchall()]
        # SQLite index_info doesn't expose DESC; our indexes use it only for
        # ordering hints — functionally equivalent ASC indexes are fine in PG.
        quoted = ", ".join(f'"{c}"' for c in icols)
        unique = "UNIQUE " if idx["unique"] else ""
        out.append(f'CREATE {unique}INDEX "{idx["name"]}" ON "{table}" ({quoted})')
    return out


def normalize(v):
    if isinstance(v, float):
        return round(v, 6)
    return v


def rows_match(a, b):
    if len(a) != len(b):
        return False
    for x, y in zip(a, b):
        if isinstance(x, float) or isinstance(y, float):
            if x is None or y is None:
                return x == y
            if not math.isclose(float(x), float(y), rel_tol=1e-9, abs_tol=1e-9):
                return False
        elif x != y:
            return False
    return True


def main() -> int:
    apply = "--apply" in sys.argv
    recreate = "--recreate" in sys.argv
    url = os.environ.get("DATABASE_URL", "").strip()
    if not url:
        print("FATAL: DATABASE_URL not set")
        return 1
    if not SQLITE_PATH.exists():
        print(f"FATAL: {SQLITE_PATH} missing")
        return 1

    sq = sqlite_conn()
    pg = psycopg.connect(url, autocommit=False)
    cur = pg.cursor()
    failures = []

    try:
        existing = {r[0] for r in cur.execute(
            "SELECT tablename FROM pg_tables WHERE schemaname='public'"
        ).fetchall()}
        clash = [t for t in TABLES if t in existing]
        if clash and not recreate:
            print(f"FATAL: tables already exist in Postgres: {clash}\n"
                  f"Re-run with --recreate to drop and rebuild.")
            return 1
        for t in reversed(TABLES):
            cur.execute(f'DROP TABLE IF EXISTS "{t}" CASCADE')

        # ── DDL ──
        for t in TABLES:
            ddl = table_ddl(sq, t)
            cur.execute(ddl)
            for iddl in index_ddls(sq, t):
                cur.execute(iddl)
        print(f"schema created: {len(TABLES)} tables")

        # ── Data ──
        for t in TABLES:
            cols = [r["name"] for r in sq.execute(f"PRAGMA table_info({t})").fetchall()]
            col_list = ", ".join(f'"{c}"' for c in cols)
            rows = [tuple(r) for r in sq.execute(f"SELECT {col_list} FROM {t}").fetchall()]
            if rows:
                ph = ", ".join("%s" for _ in cols)
                cur.executemany(
                    f'INSERT INTO "{t}" ({col_list}) VALUES ({ph})', rows
                )
            # reset identity sequence where applicable
            pkinfo = [r for r in sq.execute(f"PRAGMA table_info({t})").fetchall() if r["pk"]]
            if len(pkinfo) == 1 and (pkinfo[0]["type"] or "").upper() == "INTEGER":
                pk = pkinfo[0]["name"]
                cur.execute(
                    f"SELECT setval(pg_get_serial_sequence('\"{t}\"', '{pk}'), "
                    f"COALESCE((SELECT MAX(\"{pk}\") FROM \"{t}\"), 1))"
                )

        # ── Verify: full row-by-row, ordered by PK ──
        print()
        for t in TABLES:
            info = sq.execute(f"PRAGMA table_info({t})").fetchall()
            cols = [r["name"] for r in info]
            pks = [r["name"] for r in info if r["pk"]] or [cols[0]]
            order = ", ".join(f'"{c}"' for c in pks)
            col_list = ", ".join(f'"{c}"' for c in cols)
            s_rows = [tuple(normalize(v) for v in r) for r in
                      sq.execute(f"SELECT {col_list} FROM {t} ORDER BY {order}")]
            p_rows = [tuple(normalize(v) for v in r) for r in
                      cur.execute(f'SELECT {col_list} FROM "{t}" ORDER BY {order}').fetchall()]
            ok = len(s_rows) == len(p_rows) and all(
                rows_match(a, b) for a, b in zip(s_rows, p_rows))
            print(f"  {'OK ' if ok else 'MISMATCH'} {t:28s} sqlite={len(s_rows)} pg={len(p_rows)}")
            if not ok:
                for i, (a, b) in enumerate(zip(s_rows, p_rows)):
                    if not rows_match(a, b):
                        failures.append(f"{t} first diff at row {i}: {pks}={a[:1]}")
                        break
                if len(s_rows) != len(p_rows):
                    failures.append(f"{t}: count {len(s_rows)} vs {len(p_rows)}")

        if failures:
            print("\nFAILED:")
            for f in failures:
                print("  -", f)
            pg.rollback()
            return 1

        if apply:
            pg.commit()
            print("\nAPPLIED — Postgres is now a verified copy of foothold.db.")
        else:
            pg.rollback()
            print("\nDry run PASSED (transaction rolled back — Postgres left untouched).")
            print("Re-run with --apply to commit.")
        return 0
    finally:
        sq.close()
        pg.close()


if __name__ == "__main__":
    raise SystemExit(main())
