"""Seed: 40 NCR-listed distressed companies in priority order.

Sourced from the multi-agent research synthesis (June 2026).
Order = initial_rank = the priority you approved; not displayed in UI but
drives default sort within each temperature tab.
"""

# bucket: 'acute' / 'margin' / 'legacy'
SEED = [
    # ───── P1 / rank 1–6 ────────────────────────────────────────────
    {
        "id": "omaxe", "ticker": "OMAXE", "name": "Omaxe",
        "hq_city": "Gurgaon", "bucket": "acute", "sector": "Real Estate",
        "mcap_cr": 1389, "cap_band": "small",
        "fy26_pat": "-₹696 cr", "fy26_yoy": "worsened",
        "latest_qtr": "Q4: -₹191 cr (8th straight neg-EBITDA)",
        "stock_drawdown": "-33% from 2yr high",
        "spine": "Sales force × project completion velocity.",
        "leak": "₹1,360cr gap between FY25 bookings (~₹3,000cr) and recognised revenue (~₹1,640cr). Q4 op margin -57.94%.",
        "signal": "8 consecutive negative-EBITDA quarters; CARE downgraded BBB-/Neg → BB+/Stable Sep-24; shareholder funds NEGATIVE -₹205 cr.",
        "lever": "Sales-force productivity + lead qualification + per-project completion-risk prediction.",
        "dm_name": "Rohtas Goel", "dm_role": "Chairman & MD (founder)",
        "dm_linkedin": "",
        "initial_rank": 1,
    },
    {
        "id": "indiamart", "ticker": "INDIAMART", "name": "IndiaMART InterMESH",
        "hq_city": "Noida", "bucket": "margin", "sector": "B2B Marketplace",
        "mcap_cr": None, "cap_band": "mid",
        "fy26_pat": "+₹474.7 cr", "fy26_yoy": "-14%",
        "latest_qtr": "Q4: +₹50.2 cr (-72.2% YoY)",
        "stock_drawdown": "-34% from 52w high",
        "spine": "Paid supplier base × ARPU × tier conversion.",
        "leak": "Net 1,200 paid suppliers LOST in Q4 (total 220,000). Annual retention -10-15%. PAT margin 50.86% → 12.42% in 1 year.",
        "signal": "Management SUSPENDED guidance on net supplier additions. Stopped reporting traffic metrics in Q4 amid bot/agentic-traffic surge.",
        "lever": "Churn-prediction at Silver tier + supplier-success cost-to-serve + price-tier optimisation.",
        "dm_name": "Dinesh Agarwal", "dm_role": "Founder & MD",
        "dm_linkedin": "",
        "initial_rank": 2,
    },
    {
        "id": "bata-india", "ticker": "BATAINDIA", "name": "Bata India",
        "hq_city": "Gurgaon", "bucket": "margin", "sector": "Footwear Retail",
        "mcap_cr": 8537, "cap_band": "mid",
        "fy26_pat": "+₹133.6 cr", "fy26_yoy": "-59.3%",
        "latest_qtr": "Q4: +₹2.2 cr (-95.2% YoY)",
        "stock_drawdown": "-48% from 2yr high (₹1,300 → ~₹665)",
        "spine": "Store footprint × per-store productivity.",
        "leak": "Q4 gross margin -789bps YoY (21.04% → 13.15%). 700 ZBM doors +6.1% volume vs ~1,300 non-ZBM running NEGATIVE volume growth. Inventory cut 28% YoY via forced discount.",
        "signal": "Management explicitly cited 'aggressive discounting to clear inventory'. Multiple analyst downgrades Oct-25 to Mar-26 (JM Reduce, Axis Hold, Marketsmojo Sell).",
        "lever": "Per-door P&L visibility → speed of ZBM rollout to next 500 doors + decision on which legacy doors to shut.",
        "dm_name": "Gunjan Shah", "dm_role": "CEO & MD",
        "dm_linkedin": "",
        "initial_rank": 3,
    },
    {
        "id": "religare", "ticker": "RELIGARE", "name": "Religare Enterprises",
        "hq_city": "Delhi", "bucket": "margin", "sector": "Diversified Financials",
        "mcap_cr": 7900, "cap_band": "small-mid",
        "fy26_pat": "+₹73 cr", "fy26_yoy": "-60%",
        "latest_qtr": "Q4: +₹96 cr (-37% YoY)",
        "stock_drawdown": "-22% from Dec-24 high",
        "spine": "Care Health Insurance loss-ratio + commission-ratio (Care = 79% of group revenue).",
        "leak": "H1 FY26 Care operating loss ₹70cr — GWP +8% but claims +21% AND commission outgo ₹627cr outpaced premium growth. Underlying FY26 PAT ~breakeven once you strip non-recurring ₹93.7cr Finvest provision write-back.",
        "signal": "Burman family demerger approved May 2026 → Care Health prepping standalone listing in 12 months. ₹750cr Burman capital infusion mid-FY26.",
        "lever": "Claims fraud detection + pre-auth automation + underwriting risk-scoring + cross-LoB CLV.",
        "dm_name": "Mohit Burman", "dm_role": "Chairman (Burman family)",
        "dm_linkedin": "",
        "initial_rank": 4,
    },
    {
        "id": "ht-media", "ticker": "HTMEDIA", "name": "HT Media",
        "hq_city": "Delhi", "bucket": "legacy", "sector": "Print + Radio + Digital",
        "mcap_cr": None, "cap_band": "small",
        "fy26_pat": "+₹153 cr", "fy26_yoy": "+44%",
        "latest_qtr": "Q4: +₹96 cr (+15% YoY)",
        "stock_drawdown": "n/a (flat decade)",
        "spine": "Digital subscription pivot × ad-yield management. ₹945cr net cash waiting to be deployed.",
        "leak": "Digital segment EBITDA -₹8 cr on ₹155 cr revenue (-5% margin). OTTplay shutdown booked ₹100.96 cr loss on ₹96.64 cr revenue. Hindustan Hindi circulation -2% YoY.",
        "signal": "Surrendering 4 metro radio licences (Nasha + Radio One + Fever) on Jun 15, 2026 — stations had ₹29 cr FY25 revenue against NEGATIVE net worth -₹172 cr (10.33% of consolidated).",
        "lever": "Mint Premium dynamic paywall + programmatic ad-yield ML + LLM newsroom automation (Hindustan↔HT↔Mint vernacular translation).",
        "dm_name": "Shobhana Bhartia", "dm_role": "Chairperson (KK Birla family)",
        "dm_linkedin": "",
        "initial_rank": 5,
    },
    {
        "id": "spicejet", "ticker": "SPICEJET", "name": "SpiceJet",
        "hq_city": "Gurgaon", "bucket": "acute", "sector": "Aviation",
        "mcap_cr": 1946, "cap_band": "small",
        "fy26_pat": "-₹1,116 cr (9M)", "fy26_yoy": "4× worse",
        "latest_qtr": "Q3: -₹261 cr (Q4 pending)",
        "stock_drawdown": "-73% (₹46.9 → ₹12.8)",
        "spine": "Active fleet × yield × ancillary attach.",
        "leak": "13 of 68 aircraft active (~80% grounded) as of Apr-26. ₹2,381 cr remaining lessor liabilities; new ₹58 cr insolvency case. Foreign crew via costly ACMI wet-lease to defend slots.",
        "signal": "Going-concern auditor flag; 6-month employee furlough Apr-Sep 2026; promoter Ajay Singh diluted to 33% via ₹3,000 cr QIP Sep-24.",
        "lever": "Yield/dynamic-ancillary pricing on the 18-aircraft schedule (limited but real). NOT a balance-sheet fix.",
        "dm_name": "Ajay Singh", "dm_role": "Chairman & MD (founder)",
        "dm_linkedin": "",
        "initial_rank": 6,
    },

    # ───── P2 / rank 7–22 ───────────────────────────────────────────
    {
        "id": "igl", "ticker": "IGL", "name": "Indraprastha Gas",
        "hq_city": "Delhi", "bucket": "margin", "sector": "City Gas Distribution",
        "mcap_cr": None, "cap_band": "large",
        "fy26_pat": "Q4: +₹340.5 cr", "fy26_yoy": "Q4 -25.2% YoY",
        "latest_qtr": "Op margin 14.47% → 10.12% (-435bps from peak)",
        "stock_drawdown": "-20% single-day Nov-24 on APM cut",
        "spine": "Gas-sourcing mix (cheap APM blended with expensive LNG) × station-level volume.",
        "leak": "APM allocation cut TWICE in 30 days (Oct + Nov 2024). APM share 51% → 34%, headed to ZERO over 5 yrs. Replacement gas $9-14 vs $6.5/mmbtu APM.",
        "signal": "Delhi DTC EV bus fleet rollout eroding CNG demand. Delhi-NCR is 80-85% of IGL volume — no geographic offset.",
        "lever": "Station-level demand forecasting + LNG procurement timing + new-geography (Gurugram/Kanpur/Muzaffarnagar) expansion.",
        "dm_name": "Kamal Kishore Chatiwal", "dm_role": "MD",
        "dm_linkedin": "",
        "initial_rank": 7,
    },
    {
        "id": "tv-today", "ticker": "TVTODAY", "name": "TV Today Network",
        "hq_city": "Noida", "bucket": "legacy", "sector": "Broadcasting (Aaj Tak / India Today)",
        "mcap_cr": None, "cap_band": "small",
        "fy26_pat": "+₹13.74 cr", "fy26_yoy": "-82%",
        "latest_qtr": "Q4: +₹9 cr (rev -14.3% YoY)",
        "stock_drawdown": "n/a (revenue -₹184 cr YoY)",
        "spine": "News-genre TV ad revenue + digital Aaj Tak pivot.",
        "leak": "FY26 revenue -18.6% YoY (₹993 → ₹809 cr). Q2 FY26 swung to net loss ₹2.04 cr — first loss quarter. Radio segment also dragging.",
        "signal": "I&B Ministry froze BARC TRPs for news genre (extended 4 more weeks Apr-26). Advertisers can't price-discover news inventory → ad spend reallocating to digital.",
        "lever": "Aaj Tak digital pivot speed + digital-news monetisation.",
        "dm_name": "Aroon Purie", "dm_role": "Chairman & Editor-in-Chief (founder family)",
        "dm_linkedin": "",
        "initial_rank": 8,
    },
    {
        "id": "jbm-auto", "ticker": "JBMA", "name": "JBM Auto",
        "hq_city": "Gurgaon", "bucket": "margin", "sector": "Auto-Ancillary + EV Buses",
        "mcap_cr": 16075, "cap_band": "mid",
        "fy26_pat": "+₹238 cr", "fy26_yoy": "interest hides margin",
        "latest_qtr": "Q4: +₹84 cr; Q4 interest +47% QoQ to ₹108 cr",
        "stock_drawdown": "-35% (₹681 → ₹790 high)",
        "spine": "Working-capital cycle: EV bus delivery → state govt receivable → cash.",
        "leak": "Trade receivables DOUBLED to ₹2,185 cr (36% of assets). OCF -59% to ₹160 cr despite profit growth. Borrowings +61% to ₹2,070 cr; D/E 2.24×.",
        "signal": "Annualised interest run-rate ~₹430 cr. State govt EV bus payment lag is the bottleneck.",
        "lever": "Collections velocity per state govt customer + receivables-prediction + factoring/securitisation.",
        "dm_name": "Nishant Arya", "dm_role": "Vice-Chairman & MD",
        "dm_linkedin": "",
        "initial_rank": 9,
    },
    {
        "id": "hindware", "ticker": "HINDWAREAP", "name": "Hindware Home Innovation",
        "hq_city": "Gurgaon", "bucket": "acute", "sector": "Sanitaryware + Pipes + Furniture",
        "mcap_cr": None, "cap_band": "small",
        "fy26_pat": "-₹39 cr (consol) / -₹70.7 cr (standalone)", "fy26_yoy": "loss narrowed 42% consol",
        "latest_qtr": "Q4: -₹19 cr (rev -5% YoY)",
        "stock_drawdown": "[unverified]",
        "spine": "Bathware (working) + Pipes (broken) + EVOK Homes (dying).",
        "leak": "EVOK Homes furniture sub flagged GOING CONCERN by auditors (liabilities > assets by ₹5.55cr). Pipes segment PBT loss ₹29 cr FY26. Standalone parent loss ₹70.7 cr.",
        "signal": "Discontinuing air coolers, fans, air purifiers, water purifiers, furniture fittings. Composite Scheme of Arrangement at NCLT — dismantling holding structure.",
        "lever": "Per-format P&L visibility + speed of EVOK wind-down + pipes raw-material hedging.",
        "dm_name": "Sandip Somany", "dm_role": "Chairman & MD",
        "dm_linkedin": "",
        "initial_rank": 10,
    },
    {
        "id": "devyani", "ticker": "DEVYANI", "name": "Devyani International",
        "hq_city": "Gurgaon", "bucket": "acute", "sector": "QSR (KFC / Pizza Hut / Costa India)",
        "mcap_cr": 14641, "cap_band": "mid",
        "fy26_pat": "-₹42.5 cr", "fy26_yoy": "flipped from +₹6.9 cr",
        "latest_qtr": "Q4: -₹10 cr (rev +18.5% QoQ)",
        "stock_drawdown": "-38% (₹191 → ₹118)",
        "spine": "Brand-level same-store growth — KFC (+4.9% best in 14Q) working, Pizza Hut failing.",
        "leak": "Pizza Hut store adds collapsed 63 → 9 YoY. All CY26 Pizza Hut openings SUSPENDED. D/E 2.17× (highest in QSR sector). Borrowings doubled to ₹575 cr current + ₹786 cr non-current.",
        "signal": "Management admitted Pizza Hut 'technology missing, marketing not effective, innovation pipeline weak'. IND AS 116 lease + finance cost consumes EBITDA on every new store.",
        "lever": "Per-store P&L visibility + Pizza Hut shutdown decisions + KFC menu engineering + delivery cost optimisation.",
        "dm_name": "Ravi Jaipuria", "dm_role": "Chairman (Jaipuria family)",
        "dm_linkedin": "",
        "initial_rank": 11,
    },
    {
        "id": "whirlpool", "ticker": "WHIRLPOOL", "name": "Whirlpool of India",
        "hq_city": "Gurgaon", "bucket": "margin", "sector": "White Goods",
        "mcap_cr": 11000, "cap_band": "mid",
        "fy26_pat": "+₹293.75 cr", "fy26_yoy": "-18.2%",
        "latest_qtr": "Q4: +₹80 cr (-32.7% YoY); EBITDA -40.9% YoY",
        "stock_drawdown": "-42% from 52w high ₹1,473",
        "spine": "Dealer share defence × service margin.",
        "leak": "Q4 EBITDA -41% on revenue +7.4%. Steel/copper/plastic input inflation could not be passed through 'due to competitive dynamics and price-sensitive demand'. Decadal op margin decay 11.2% (FY20) → 5.6% (Q4 FY26).",
        "signal": "New BEE/efficiency norms = permanent BOM step-up. E-waste rules added Q4 cost. AC working capital build.",
        "lever": "Service margin recovery + dealer-mix shift away from discount-led volume + AC inventory optimisation.",
        "dm_name": "Narasimhan Eswar", "dm_role": "MD",
        "dm_linkedin": "",
        "initial_rank": 12,
    },
    {
        "id": "ndtv", "ticker": "NDTV", "name": "New Delhi Television",
        "hq_city": "Delhi", "bucket": "acute", "sector": "Broadcasting (Adani-owned)",
        "mcap_cr": None, "cap_band": "small",
        "fy26_pat": "-₹323 cr", "fy26_yoy": "-48% deeper",
        "latest_qtr": "Q4: -₹97.84 cr (10th straight loss qtr)",
        "stock_drawdown": "[unverified]",
        "spine": "Adani-funded share-of-voice expansion through losses.",
        "leak": "Revenue +13.6% but losses widened 48%; costs +24% YoY (₹689 → ₹855 cr). Marketing spend ₹243 cr = 44.7% of revenue. NDTV World + NDTV Marathi channel build-out.",
        "signal": "Production expenses Q4 +64% YoY. BARC TRP freeze hits news ad pricing same as TV Today.",
        "lever": "Cost-line discipline + digital monetisation. But Adani holds 64.7% → decision lives at group level, not at NDTV CFO.",
        "dm_name": "Sanjay Pugalia", "dm_role": "CEO (Adani group)",
        "dm_linkedin": "",
        "initial_rank": 13,
    },
    {
        "id": "indus-towers", "ticker": "INDUSTOWER", "name": "Indus Towers",
        "hq_city": "Gurgaon", "bucket": "margin", "sector": "Telecom Towers",
        "mcap_cr": None, "cap_band": "large",
        "fy26_pat": "+₹7,145 cr", "fy26_yoy": "-28.05%",
        "latest_qtr": "Q4: +₹1,793 cr (flat); revenue +7.86%",
        "stock_drawdown": "-29% (₹460 → ₹325 Apr-26)",
        "spine": "Tenancy ratio × Vi credit-risk.",
        "leak": "FY25 had ₹50.9bn bad-debt reversal (Vi paid up); FY26 only ₹2.7bn — one-off tailwind gone. Vi = 20% of revenue still under stress.",
        "signal": "Incremental tenancy ratio softened to 1.48×. US 26% reciprocal tariff Apr-26 triggered FII outflow.",
        "lever": "Vi collections discipline + Jio/Airtel tenancy adds per geography.",
        "dm_name": "Prachur Sah", "dm_role": "MD & CEO",
        "dm_linkedin": "",
        "initial_rank": 14,
    },
    {
        "id": "rba-burger-king", "ticker": "RBA", "name": "Restaurant Brands Asia (Burger King India)",
        "hq_city": "Mumbai regd / NCR ops", "bucket": "legacy", "sector": "QSR",
        "mcap_cr": 3949, "cap_band": "small",
        "fy26_pat": "-₹204 cr (consol) / -₹159 cr (standalone)", "fy26_yoy": "8 straight loss qtrs",
        "latest_qtr": "Q4: -₹43 cr",
        "stock_drawdown": "at 52w lows (₹67.69)",
        "spine": "India SSG + Indonesia subsidiary.",
        "leak": "₹120 cr Indonesia impairment FY26 (full write-down). India SSG only +4% for full year — below food inflation. Q4 EBITDA ₹95 cr consumed by ₹49.8 cr interest + ₹100.7 cr depreciation.",
        "signal": "QSR Asia (sponsor) CCI-approved control change at ₹70.39/share — ownership churning mid-bleed.",
        "lever": "Indonesia exit speed + India menu re-pricing + per-store P&L. But QSR Asia transition limits decision velocity.",
        "dm_name": "Rajeev Varman", "dm_role": "CEO",
        "dm_linkedin": "",
        "initial_rank": 15,
    },
    {
        "id": "relaxo", "ticker": "RELAXO", "name": "Relaxo Footwears",
        "hq_city": "Delhi", "bucket": "margin", "sector": "Mass-Market Footwear",
        "mcap_cr": 8400, "cap_band": "mid",
        "fy26_pat": "+₹179.3 cr", "fy26_yoy": "+5.3% but revenue -3.1%",
        "latest_qtr": "Q4: +₹68 cr; FY revenue ₹2,702 cr (-3.1%)",
        "stock_drawdown": "-40 to -57% (₹704 → ₹299-421)",
        "spine": "General-trade distribution to Tier-3 mass market.",
        "leak": "Q2 volumes -4.7% YoY; Q3 PAT -19.6% YoY, EBITDA margin collapsed to 10.4%. FY26 revenue declined — rare for this growth-stock.",
        "signal": "CFO Prince Jain resigned with IMMEDIATE EFFECT Mar 11, 2026, mid-margin-crisis. New CFO Amit Roy Apr-1.",
        "lever": "Distributor productivity ranking + secondary-sales tracking + channel discipline.",
        "dm_name": "Ramesh Kumar Dua", "dm_role": "MD (founder family)",
        "dm_linkedin": "",
        "initial_rank": 16,
    },
    {
        "id": "smc-global", "ticker": "SMCGLOBAL", "name": "SMC Global Securities",
        "hq_city": "Delhi", "bucket": "margin", "sector": "Broking + Insurance Broking",
        "mcap_cr": 620, "cap_band": "micro",
        "fy26_pat": "+₹103.2 cr", "fy26_yoy": "-29.7%",
        "latest_qtr": "Q4: +₹21.5 cr (base effect)",
        "stock_drawdown": "-37% (₹94.9 → ₹59.88)",
        "spine": "Active client base × F&O notional + insurance-broking hedge.",
        "leak": "SEBI Nov-24 F&O reform tripled contract value (₹5-10L → ₹15-20L) and lot size (25 → 75). NSE active client base -7% in FY26 (35 lakh accounts lost). Sub-scale broker = worst hit.",
        "signal": "Insurance broking +17% YoY, now 34% of mix — masking core broking decline. ~58% of one promoter entity's shares encumbered.",
        "lever": "Insurance broking scale-up speed + cross-sell across broking-lending-insurance.",
        "dm_name": "Subhash Aggarwal", "dm_role": "Chairman & MD (founder)",
        "dm_linkedin": "",
        "initial_rank": 17,
    },
    {
        "id": "jubilant-foodworks", "ticker": "JUBLFOOD", "name": "Jubilant FoodWorks",
        "hq_city": "Noida", "bucket": "margin", "sector": "QSR (Domino's India)",
        "mcap_cr": None, "cap_band": "large",
        "fy26_pat": "growth", "fy26_yoy": "Domino's SSG 0.2%",
        "latest_qtr": "Q4: +₹93.5 cr (+67.2% YoY)",
        "stock_drawdown": "-8% intraday on Q4 results",
        "spine": "Domino's same-store growth + delivery efficiency.",
        "leak": "Domino's India SSG 0.2% — essentially zero throughput growth. Headline revenue +19% from store count only. Affordability strategy = ASP pressure.",
        "signal": "Popeyes +28% SSG masks Domino's stagnation; Popeyes still tiny absolute base. DP Eurasia (Turkey) lira drag.",
        "lever": "Menu engineering + value-tier traffic recovery + delivery cost-per-order optimisation.",
        "dm_name": "Sameer Khetarpal", "dm_role": "CEO & MD",
        "dm_linkedin": "",
        "initial_rank": 18,
    },
    {
        "id": "dr-lal", "ticker": "LALPATHLAB", "name": "Dr Lal PathLabs",
        "hq_city": "Delhi", "bucket": "margin", "sector": "Diagnostics",
        "mcap_cr": None, "cap_band": "mid",
        "fy26_pat": "+₹510 cr", "fy26_yoy": "+3.7%",
        "latest_qtr": "Q4: +₹132 cr (-15.1% YoY)",
        "stock_drawdown": "-20.5% (₹1,771 → ₹1,148)",
        "spine": "Patient acquisition × per-patient revenue × doctor-referral network.",
        "leak": "Q4 patient volumes only +2.7%; ₹30 cr Labour Code one-off. Q4 EBITDA margin 26.6% vs 28.1% YoY (-150bps).",
        "signal": "Tata 1mg offered Thyroid/Lipid/Diabetes/Liver panels at FLAT ₹100 vs industry ₹500-600. PharmEasy controls 66.1% of Thyrocare.",
        "lever": "Doctor-referral CRM + B2B hospital/clinic contracts + per-test profitability ranking.",
        "dm_name": "Bharath U.", "dm_role": "CEO",
        "dm_linkedin": "",
        "initial_rank": 19,
    },
    {
        "id": "capital-india-finance", "ticker": "CIFL", "name": "Capital India Finance",
        "hq_city": "Delhi", "bucket": "acute", "sector": "NBFC (MSME)",
        "mcap_cr": 1133, "cap_band": "micro",
        "fy26_pat": "+₹40 cr (incl ₹267cr CIHL exit gain)", "fy26_yoy": "+243% headline misleading",
        "latest_qtr": "Q4: -₹2.98 cr standalone",
        "stock_drawdown": "-32% (₹44.5 → ₹30)",
        "spine": "MSME book + cost-to-serve.",
        "leak": "Q4 revenue -14.9% QoQ, -10.2% YoY. 5 consecutive loss quarters at consolidated level. Interest ₹21.72 cr consumed quarterly top-line ₹125 cr.",
        "signal": "₹267cr CIHL home-loan divestment Aug-25 propped FY26 headline. Asset quality OK (NNPA 1.32%, CAR 40.99%) — pure yield/cost mismatch.",
        "lever": "Sourcing-channel quality (which DSAs/branches produce profitable MSME loans) + collections velocity + branch-level P&L.",
        "dm_name": "Keshav Porwal", "dm_role": "MD",
        "dm_linkedin": "",
        "initial_rank": 20,
    },
    {
        "id": "maruti", "ticker": "MARUTI", "name": "Maruti Suzuki India",
        "hq_city": "Delhi", "bucket": "margin", "sector": "Auto OEM (PV)",
        "mcap_cr": 404000, "cap_band": "large",
        "fy26_pat": "record revenue +20%", "fy26_yoy": "PAT margin -276bps",
        "latest_qtr": "Q4: +₹3,659 cr (-6.4% YoY)",
        "stock_drawdown": "-15% post-results",
        "spine": "Dealer discount intensity × entry-vs-Nexa product mix.",
        "leak": "Q4 PAT margin 10.07% → 7.31% (-276bps YoY). Input inflation ₹12,000-18,000/vehicle FY26 → forced ₹30,000 across-the-board price hike Jun-26.",
        "signal": "Maruti dealer discounts up to ₹70,000 in May 2026. Royalty to Suzuki ~₹4,500 cr/year (FY23 disclosed) — growing absolute drag.",
        "lever": "Dynamic dealer-incentive engine + per-dealer inventory optimisation + Nexa premium mix push.",
        "dm_name": "Hisashi Takeuchi", "dm_role": "MD & CEO",
        "dm_linkedin": "",
        "initial_rank": 21,
    },
    {
        "id": "vodafone-idea", "ticker": "IDEA", "name": "Vodafone Idea",
        "hq_city": "Mumbai regd / NCR ops", "bucket": "acute", "sector": "Telecom",
        "mcap_cr": None, "cap_band": "large",
        "fy26_pat": "+₹51,970 cr headline / underlying -₹5,515 cr Q4", "fy26_yoy": "AGR one-off masks operating loss",
        "latest_qtr": "Q4 underlying loss ₹5,515 cr",
        "stock_drawdown": "52w high ₹15.25 / low ₹6.12",
        "spine": "ARPU × subscriber base × AGR liability servicing.",
        "leak": "6th consecutive year operating losses ex-one-off. AGR liability still ₹64,046 cr post-DoT revision. Subscriber adds turned positive only Feb-26.",
        "signal": "Government equity stake propping unviable balance sheet. ARPU ₹190 (+₹15 YoY).",
        "lever": "Network AI + churn — but real decisions live at parent / Govt level. Realistic AI-vendor wedge = LOW.",
        "dm_name": "Akshaya Moondra", "dm_role": "CEO",
        "dm_linkedin": "",
        "initial_rank": 22,
    },

    # ───── P3 / rank 23–38 ──────────────────────────────────────────
    {
        "id": "dixon-tech", "ticker": "DIXON", "name": "Dixon Technologies",
        "hq_city": "Noida", "bucket": "margin", "sector": "Electronics Mfg Services",
        "mcap_cr": None, "cap_band": "large",
        "fy26_pat": "Q4: +₹256.4 cr (-36% YoY)", "fy26_yoy": "rev flat +2.1%",
        "latest_qtr": "Q4 EBITDA 4.0% (vs 4.4% YoY)",
        "stock_drawdown": "-5.87% on Q4 results",
        "spine": "Per-line utilisation × customer mix (mobile vs IT-hardware vs new categories).",
        "leak": "Q4 employee costs +21.4% on revenue +2.1% = severe operating leverage break. Memory chip price inflation + soft mobile demand.",
        "signal": "Vivo JV uncertainty flagged by analysts. Stock dropped on results.",
        "lever": "Customer-profitability ranking + line-allocation by customer + JV decision clarity.",
        "dm_name": "Atul B. Lall", "dm_role": "Vice-Chairman & MD",
        "dm_linkedin": "",
        "initial_rank": 23,
    },
    {
        "id": "sammaan-capital", "ticker": "SAMMAANCAP", "name": "Sammaan Capital (ex-Indiabulls Housing)",
        "hq_city": "Gurgaon", "bucket": "acute", "sector": "Housing Finance NBFC",
        "mcap_cr": 16500, "cap_band": "mid",
        "fy26_pat": "-₹7,145 cr (cleanup)", "fy26_yoy": "Q1-Q3 were +₹300 cr/qtr",
        "latest_qtr": "Q4: -₹8,101 cr (kitchen-sink)",
        "stock_drawdown": "+7% on the loss (read as cleanup)",
        "spine": "Legacy developer book runoff + retail mortgage scale-up.",
        "leak": "Q4 ₹6,499 cr exceptional on ₹14,953 cr non-core sale to ARC + ₹2,958 cr impairment + ₹1,850 cr management overlay ECL.",
        "signal": "₹8,850 cr capital infusion from Abu Dhabi IHC. CRISIL + CARE upgrades post-cleanup. Net D/E 2.04×.",
        "lever": "Early-warning credit ML on residual book + retail-mortgage underwriting automation. But likely in-house team already.",
        "dm_name": "Gagan Banga", "dm_role": "Vice-Chairman & MD",
        "dm_linkedin": "",
        "initial_rank": 24,
    },
    {
        "id": "almondz", "ticker": "ALMONDZ", "name": "Almondz Global Securities",
        "hq_city": "Delhi", "bucket": "margin", "sector": "Capital Markets",
        "mcap_cr": 145, "cap_band": "micro",
        "fy26_pat": "+₹28.7 cr", "fy26_yoy": "+66% headline / Q4 collapse",
        "latest_qtr": "Q4: +₹5.18 cr (-59% QoQ)",
        "stock_drawdown": "-44% from ₹26.6 high",
        "spine": "Capital-markets vs advisory revenue mix.",
        "leak": "Q4 OPM 21.46% → 5.22% (-1,624bps) on record revenue. Mix shifted to low-margin advisory/syndication/green fuel.",
        "signal": "Promoter holding -8.92% over 3 yrs via warrant issuance at discount.",
        "lever": "Revenue-mix discipline: say no to low-margin mandates.",
        "dm_name": "Navjeet Singh Sobti", "dm_role": "MD",
        "dm_linkedin": "",
        "initial_rank": 25,
    },
    {
        "id": "optiemus", "ticker": "OPTIEMUS", "name": "Optiemus Infracom",
        "hq_city": "Noida", "bucket": "margin", "sector": "Mobile Distribution + EMS",
        "mcap_cr": None, "cap_band": "small",
        "fy26_pat": "+₹66 cr", "fy26_yoy": "revenue -6.4%",
        "latest_qtr": "Q4: +₹22.5 cr; OPM 1.46% (8Q low)",
        "stock_drawdown": "-34% (₹713 → ₹325)",
        "spine": "Mobile distribution thin margin + EMS scale-up.",
        "leak": "Q4 other income = 66.34% of PBT. EBIT/Interest = -1.50× (can't cover interest from ops). ROCE only 5.92%.",
        "signal": "Trading below all moving averages; 'Strong Sell' technical grade.",
        "lever": "EMS contract win velocity + distribution-channel rationalisation.",
        "dm_name": "Ashok Gupta", "dm_role": "Chairman & MD",
        "dm_linkedin": "",
        "initial_rank": 26,
    },
    {
        "id": "subros", "ticker": "SUBROS", "name": "Subros",
        "hq_city": "Delhi regd / Noida plants", "bucket": "margin", "sector": "Auto-Ancillary (AC kits)",
        "mcap_cr": 4723, "cap_band": "small-mid",
        "fy26_pat": "revenue +11.5%", "fy26_yoy": "EBITDA margin -141bps",
        "latest_qtr": "Q4: +₹49.3 cr; margin 4.70% vs 5.09% YoY",
        "stock_drawdown": "-42% (₹699 vs ₹1,213.7 high)",
        "spine": "Maruti share concentration (~60%) + thermal-mgmt EV ramp.",
        "leak": "Forex headwind on imported compressor sub-assemblies. ₹175 cr EV-compressor capex driving depreciation drag before volume.",
        "signal": "Mix shift toward lower-realisation EV thermal mgmt during ramp-up.",
        "lever": "Customer-mix diversification (Mahindra/Tata <15% combined) + faster contract escalation cycle.",
        "dm_name": "Shradha Suri Marwah", "dm_role": "Chairperson & MD",
        "dm_linkedin": "",
        "initial_rank": 27,
    },
    {
        "id": "mankind-pharma", "ticker": "MANKIND", "name": "Mankind Pharma",
        "hq_city": "Delhi", "bucket": "margin", "sector": "Branded Generics",
        "mcap_cr": None, "cap_band": "large",
        "fy26_pat": "+₹1,938 cr", "fy26_yoy": "-3.4% despite rev +17%",
        "latest_qtr": "Q3: +₹414 cr",
        "stock_drawdown": "[unverified]",
        "spine": "Chronic prescription share × MR productivity × BSV synergy.",
        "leak": "Long-term debt ₹25 cr (Mar-24) → ₹5,526 cr (Mar-25) = 222× growth from BSV ₹13,768 cr deal. Q3 interest +22.1× YoY to ₹157 cr.",
        "signal": "Organic India formulation growth only +9.1% — most of headline +17% is BSV consolidation. BSV brands Foligraf +52%, Ossopan +72%, Lactare +46%.",
        "lever": "MR productivity in chronic + BSV cross-sell via Mankind's distribution.",
        "dm_name": "Rajeev Juneja", "dm_role": "Vice-Chairman & MD",
        "dm_linkedin": "",
        "initial_rank": 28,
    },
    {
        "id": "panacea-biotec", "ticker": "PANACEABIO", "name": "Panacea Biotec",
        "hq_city": "Delhi", "bucket": "acute", "sector": "Pharma / Vaccines",
        "mcap_cr": 3457, "cap_band": "small",
        "fy26_pat": "-₹9.89 cr", "fy26_yoy": "volatile, not chronic",
        "latest_qtr": "Q4: -₹1.0 cr (Q4 OPM 1.54% from 7.11%)",
        "stock_drawdown": "~49% from 52w high ₹581",
        "spine": "Easyfive pentavalent vaccine to UNICEF + Indofil legacy.",
        "leak": "Q4 OPM collapsed 556bps QoQ. Personnel expenses Q4 ₹46.82 cr = 28.08% of net sales.",
        "signal": "Easyfive lost WHO prequalification 2019; back in supply but trust-damage legacy. Interest coverage -8.48×. 'Strong Sell' rating.",
        "lever": "Margin discipline on UNICEF tender pricing + legacy debt restructuring follow-through.",
        "dm_name": "Rajesh Jain", "dm_role": "Joint MD",
        "dm_linkedin": "",
        "initial_rank": 29,
    },
    {
        "id": "niit-ltd", "ticker": "NIITLTD", "name": "NIIT Ltd",
        "hq_city": "Gurgaon", "bucket": "legacy", "sector": "Corporate Learning Rump",
        "mcap_cr": 1400, "cap_band": "small",
        "fy26_pat": "+₹6.14 cr consol / -₹10.3 cr standalone", "fy26_yoy": "revenue -9% YoY",
        "latest_qtr": "Q4 standalone -₹4.4 cr (swung from +₹13 cr FY25)",
        "stock_drawdown": "near 52w low ~₹103",
        "spine": "Treasury yield from demerger cash pile.",
        "leak": "Q3 FY26 other income = 171.97% of PBT — operations loss-making. Standalone loss ₹10.3 cr in both FY25 AND FY26.",
        "signal": "Surviving on treasury income after profitable Learning Systems spinoff.",
        "lever": "Capital deployment decision: redeploy cash OR return to shareholders. No operational lever inside the rump.",
        "dm_name": "Rajendra Singh Pawar", "dm_role": "Chairman (founder)",
        "dm_linkedin": "",
        "initial_rank": 30,
    },
    {
        "id": "munjal-showa", "ticker": "MUNJALSHOW", "name": "Munjal Showa",
        "hq_city": "Gurgaon (Manesar)", "bucket": "margin", "sector": "Auto-Ancillary (Shocks)",
        "mcap_cr": 553, "cap_band": "small",
        "fy26_pat": "+₹21.87 cr", "fy26_yoy": "-24.3% (revenue +5.2%)",
        "latest_qtr": "Q4: -₹0.05 cr — first loss in 8Q",
        "stock_drawdown": "~-35% from 2yr peak",
        "spine": "Hero MotoCorp (sole customer for shocks).",
        "leak": "Q4 gross margin 4.96% → 1.08% QoQ (-388bps at gross). Steel + alloy not passed through.",
        "signal": "Hero's own margin pressure transmitted directly. Hero-Hitachi Astemo JV royalty/licensing continues regardless.",
        "lever": "Customer diversification (Bajaj/TVS/HMSI) — there's no internal lever; the case is 'win a second customer'.",
        "dm_name": "Pankaj Munjal", "dm_role": "Chairman (Munjal family)",
        "dm_linkedin": "",
        "initial_rank": 31,
    },
    {
        "id": "amber-enterprises", "ticker": "AMBER", "name": "Amber Enterprises",
        "hq_city": "Gurgaon", "bucket": "margin", "sector": "AC OEM + Defense JV",
        "mcap_cr": None, "cap_band": "mid",
        "fy26_pat": "+₹226.45 cr", "fy26_yoy": "-9.83% despite rev +22.5%",
        "latest_qtr": "Q4: +₹133.88 cr (+15.34% YoY)",
        "stock_drawdown": "-15% on annual results",
        "spine": "AC OEM share (LG/Voltas/Daikin) + Railway/Defense electronics JV.",
        "leak": "JV losses BALLOONED to ₹90 cr in FY26 vs ₹30 cr FY25 — Railway/Defense JV alone ₹83 cr drag.",
        "signal": "Statutory auditors issued QUALIFIED OPINION — unaudited subsidiary data in consolidated results.",
        "lever": "JV exit / wind-down decision speed.",
        "dm_name": "Jasbir Singh", "dm_role": "Chairman & CEO",
        "dm_linkedin": "",
        "initial_rank": 32,
    },
    {
        "id": "jp-power", "ticker": "JPPOWER", "name": "Jaiprakash Power Ventures",
        "hq_city": "Noida", "bucket": "margin", "sector": "Thermal Power",
        "mcap_cr": 12500, "cap_band": "small",
        "fy26_pat": "+₹441.5 cr", "fy26_yoy": "-45.5%",
        "latest_qtr": "Q4: -₹13.4 cr; op margin 28.97% → 8.75%",
        "stock_drawdown": "~-40% [unverified]",
        "spine": "PPA tariff (stable) vs merchant IEX tariff (volatile) + captive coal vs e-auction.",
        "leak": "Nigrie 1,320 MW has PPA for only 37.5% of capacity; rest sells merchant. Captive Amelia mine supplies only 66% of fuel; remaining ~2 MTPA via e-auction at spot.",
        "signal": "Q4 other income ₹84.36 cr = 4,260% of PBT — core power loss-making at operating level. Adani Power buying 24% stake from JAL CIRP estate.",
        "lever": "PPA renegotiation + captive mine throughput + e-auction coal optimisation.",
        "dm_name": "Suren Jain", "dm_role": "MD & CFO",
        "dm_linkedin": "",
        "initial_rank": 33,
    },
    {
        "id": "jubilant-pharmova", "ticker": "JUBLPHARMA", "name": "Jubilant Pharmova",
        "hq_city": "Noida", "bucket": "margin", "sector": "CDMO + Radiopharma",
        "mcap_cr": None, "cap_band": "mid",
        "fy26_pat": "rev ₹8,280 cr +14%", "fy26_yoy": "Q3 PAT -53% QoQ",
        "latest_qtr": "Q3: +₹55.9 cr (-44.6% YoY)",
        "stock_drawdown": "[unverified]",
        "spine": "Montreal CDMO facility uptime + SPECT radiopharma volume.",
        "leak": "Montreal Sterile Injectables temporarily shut for FDA remediation. Q3 OPM 17.44% → 13.68%. PAT margin 6.12% → 2.64% QoQ.",
        "signal": "USFDA: Roorkee 4 observations Aug-25; Salisbury 5 observations Jan-25 (site closed).",
        "lever": "Remediation speed + tech-transfer to alternate facility.",
        "dm_name": "Shyam S. Bhartia", "dm_role": "Chairman (Jubilant Bhartia)",
        "dm_linkedin": "",
        "initial_rank": 34,
    },
    {
        "id": "hcl-tech", "ticker": "HCLTECH", "name": "HCL Technologies",
        "hq_city": "Noida", "bucket": "margin", "sector": "IT Services",
        "mcap_cr": None, "cap_band": "large",
        "fy26_pat": "+₹17,000+ cr (approx)", "fy26_yoy": "EBIT margin -107bps; FY27 guide cut",
        "latest_qtr": "Q4: +₹4,488 cr (+4.2% YoY); EBIT margin 16.5% vs 18.6% QoQ",
        "stock_drawdown": "~-23% (90-day fall to ₹1,147)",
        "spine": "Top-30 vertical accounts (Telecom + Financial Services + Manufacturing).",
        "leak": "2 large US telecom clients reduced discretionary spend on digital + ER&D — continues 'rest of CY26'. 2 SAP programs discontinued (mfg + retail).",
        "signal": "FY27 revenue guide CUT to 1.0-4.0% CC (services 1.5-4.5%). Stock hit 52-wk low post-results.",
        "lever": "Account diversification + GenAI deal velocity + customer-concentration risk mgmt.",
        "dm_name": "C. Vijayakumar", "dm_role": "CEO & MD",
        "dm_linkedin": "",
        "initial_rank": 35,
    },
    {
        "id": "sandhar-tech", "ticker": "SANDHAR", "name": "Sandhar Technologies",
        "hq_city": "Gurgaon", "bucket": "margin", "sector": "Auto-Ancillary",
        "mcap_cr": 4061, "cap_band": "small-mid",
        "fy26_pat": "rev ₹4,852 cr +25%", "fy26_yoy": "EBITDA margin 9.9% → 9.0%",
        "latest_qtr": "Q4: +₹64 cr (+50% YoY headline; supported by other income/lower tax)",
        "stock_drawdown": "~-15-20% from FY24 peak ₹697.6",
        "spine": "Plant utilisation × per-unit realisation × overseas subs turnaround.",
        "leak": "Net adjusted leverage rose to 2.5×. Q3 PAT margin 5.78% → 2.82%. Overseas subs (Spain/Poland) continued drag.",
        "signal": "Below mgmt own 10% EBITDA guidance. Heavy capex on aluminium die-casting + EV components → depreciation step-up.",
        "lever": "Capacity utilisation ramp + Spain/Poland exit decision speed.",
        "dm_name": "Jayant Davar", "dm_role": "Founder & Co-Chairman",
        "dm_linkedin": "",
        "initial_rank": 36,
    },
    {
        "id": "rico-auto", "ticker": "RICOAUTO", "name": "Rico Auto Industries",
        "hq_city": "Gurgaon", "bucket": "margin", "sector": "Auto-Ancillary (Aluminium Die-Cast)",
        "mcap_cr": 1684, "cap_band": "small",
        "fy26_pat": "+₹50.5 cr", "fy26_yoy": "rev +12%, margin lags",
        "latest_qtr": "Q4 EBITDA margin 7.1% (8Q low)",
        "stock_drawdown": "-15-20% (from ~₹142 high)",
        "spine": "Aluminium price pass-through to Hero/Bajaj/HMSI + plant utilisation.",
        "leak": "New Labour Code one-time ₹7.38 cr FY26; ₹11 cr Q4 RM lag. EBITDA margin Q4 unadjusted 7.1% vs adjusted 9.8% = ~270bps gap.",
        "signal": "CFO: 'customer renegotiation cycle ongoing — uncertainty on full recovery'. Aluminium die-casting at sub-80% utilisation.",
        "lever": "Procurement hedging + faster pass-through + capacity utilisation ramp.",
        "dm_name": "Arvind Kapur", "dm_role": "Chairman & MD",
        "dm_linkedin": "",
        "initial_rank": 37,
    },
    {
        "id": "den-networks", "ticker": "DEN", "name": "DEN Networks",
        "hq_city": "Noida", "bucket": "legacy", "sector": "Cable TV + Broadband (Reliance owned)",
        "mcap_cr": None, "cap_band": "small",
        "fy26_pat": "+₹165.77 cr", "fy26_yoy": "-17%",
        "latest_qtr": "Q4: +₹38.4 cr (-38.24% YoY)",
        "stock_drawdown": "[unverified]",
        "spine": "Cable distribution + broadband.",
        "leak": "BOTH cable AND broadband segments posted operating losses for full year. Q4 operating margin 11.46% → 6.37% YoY (-508bps).",
        "signal": "DTH + OTT structural erosion of cable. Q4 op profit ex-other-income fell 46.08% YoY.",
        "lever": "Broadband unit economics (why is DEN losing on broadband when JioFiber/Airtel are winning?).",
        "dm_name": "S.N. Sharma", "dm_role": "CEO",
        "dm_linkedin": "",
        "initial_rank": 38,
    },

    # ───── P4 / rank 39–40 ──────────────────────────────────────────
    {
        "id": "honda-power", "ticker": "HONDAPOWER", "name": "Honda India Power Products",
        "hq_city": "Greater Noida", "bucket": "margin", "sector": "Portable Gensets",
        "mcap_cr": 2300, "cap_band": "micro",
        "fy26_pat": "+₹64.24 cr", "fy26_yoy": "-19.6%",
        "latest_qtr": "Q4: +₹26.9 cr (-25.5% YoY); EBITDA margin -482bps",
        "stock_drawdown": "-29.7% from ₹3,251 high",
        "spine": "Premium portable genset ASP defence vs Greaves/Mahindra Powerol commoditisation.",
        "leak": "Q4 top-line -1.5% YoY (over-built Q3 dealer inventory then Q4 discounting). EBITDA margin 16.15% → 11.33%.",
        "signal": "Greaves' scale ~₹1,938 cr vs Honda's ₹865 cr = price-undercutting leverage.",
        "lever": "Service margin recovery + B2B genset-rental shift away from B2C volume.",
        "dm_name": "Takahiro Ueda", "dm_role": "President (Honda Motor sub)",
        "dm_linkedin": "",
        "initial_rank": 39,
    },
    {
        "id": "hi-tech-gears", "ticker": "HITECHGEAR", "name": "Hi-Tech Gears",
        "hq_city": "Gurgaon (Manesar)", "bucket": "margin", "sector": "Transmission Gears",
        "mcap_cr": 1058, "cap_band": "small",
        "fy26_pat": "Q3: +₹0.9 cr (PAT -87% YoY)", "fy26_yoy": "EBITDA -17.7% on rev +9%",
        "latest_qtr": "Q3 PAT margin 0.4%",
        "stock_drawdown": "-36% (from ~₹897 high)",
        "spine": "Plant utilisation + ICE→EV product migration + NCLAT outcome.",
        "leak": "Operational overhead of fighting CIRP — legal cost + supplier hesitance + customer caution = working-capital drag. ICE gear capacity under-utilised.",
        "signal": "NCLAT insolvency stay (Happy Forgings filing) extended to Jul 10, 2026. Separate Section 9 case by Amrop India.",
        "lever": "EV transmission / e-axle pivot speed + NCLAT outcome.",
        "dm_name": "Anil Kumar Aggarwal", "dm_role": "Chairman & MD",
        "dm_linkedin": "",
        "initial_rank": 40,
    },
]
